// generators/client/templates/react/src/main/webapp/app/modules/administration/health/health-modal.tsx
import * as React from 'react';
import { Table, Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';

const formatDiskSpaceOutput = rawValue => {
  // Should display storage space in an human readable unit
  const val = rawValue / 1073741824;
  if (val > 1) {
    // Value
    return val.toFixed(2) + ' GB';
  } else {
    return (rawValue / 1048576).toFixed(2) + ' MB';
  }
};

const HealthModal = ({ handleClose, healthObject, showModal }) => {
  const data = healthObject.details || {};
  return (
    <Modal isOpen={showModal} modalTransition={{ timeout: 20 }} backdropTransition={{ timeout: 10 }} toggle={handleClose}>
      <ModalHeader toggle={handleClose}>{healthObject.name}</ModalHeader>
      <ModalBody>
        <Table bordered>
          <thead>
            <tr>
              <th>Name</th>
              <th>Value</th>
            </tr>
          </thead>
          <tbody>
            {Object.keys(data).map((key, index) => (
              <tr key={index}>
                <td>{key}</td>
                <td>{(healthObject.name === 'diskSpace') ? formatDiskSpaceOutput(data[key]) : data[key] }</td>
              </tr>
            ))}
          </tbody>
        </Table>
      </ModalBody>
      <ModalFooter>
        <Button color="primary" onClick={handleClose}>
          Close
        </Button>
      </ModalFooter>
    </Modal>
)};

export default HealthModal;

// sandraapp/src/main/webapp/app/admin/health/health-modal.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { HealthKey, HealthDetails } from './health.service';

@Component({
  selector: 'jhi-health-modal',
  templateUrl: './health-modal.component.html',
})
export class HealthModalComponent {
  health?: { key: HealthKey; value: HealthDetails };

  constructor(public activeModal: NgbActiveModal) {}

  readableValue(value: any): string {
    if (this.health && this.health.key === 'diskSpace') {
      // Should display storage space in an human readable unit
      const val = value / 1073741824;
      if (val > 1) {
        // Value
        return val.toFixed(2) + ' GB';
      } else {
        return (value / 1048576).toFixed(2) + ' MB';
      }
    }

    if (typeof value === 'object') {
      return JSON.stringify(value);
    } else {
      return value.toString();
    }
  }

  dismiss(): void {
    this.activeModal.dismiss();
  }
}

<div class="modal-header">
    <h4 class="modal-title" id="showHealthLabel" *ngIf="health">
        <span class="text-capitalize">{{ health.key }}</span>
    </h4>

    <button aria-label="Close" data-dismiss="modal" class="close" type="button" (click)="dismiss()">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

<div class="modal-body pad">
    <div *ngIf="health">
        <h5>Properties</h5>

        <div class="table-responsive">
            <table class="table table-striped" aria-describedby="showHealthLabel">
                <thead>
                    <tr>
                        <th scope="col" class="text-left">Name</th>
                        <th scope="col" class="text-left">Value</th>
                    </tr>
                </thead>
                <tbody>
                    <tr *ngFor="let healthDetail of health.value.details | keys">
                        <td class="text-left">{{ healthDetail.key }}</td>
                        <td class="text-left">{{ readableValue(healthDetail.value) }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal-footer">
    <button data-dismiss="modal" class="btn btn-secondary float-left" type="button" (click)="dismiss()">Done</button>
</div>
