// generators/client/templates/webapp/app/components/account/Sessions.vue
<template>
    <div>
        <h2 v-if="account"><span v-bind:value="$t('sessions.title')">Active sessions for [<b>{{username}}</b>]</span></h2>

        <div class="alert alert-success" v-if="success" v-html="$t('sessions.messages.success')">
            <strong>Session invalidated!</strong>
        </div>
        <div class="alert alert-danger" v-if="error" v-html="$t('sessions.messages.error')">
            <strong>An error has occured!</strong> The session could not be invalidated.
        </div>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-text="$t('sessions.table.ipaddress')">IP Address</th>
                    <th v-text="$t('sessions.table.useragent')">User agent</th>
                    <th v-text="$t('sessions.table.date')">Date</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="session in sessions">
                    <td>{{session.ipAddress}}</td>
                    <td>{{session.userAgent}}</td>
                    <td>{{session.tokenDate}}</td>
                    <td>
                        <button type="submit"
                                class="btn btn-primary"
                                v-on:click="invalidate(session.series)" v-text="$t('sessions.table.button')">
                            Invalidate
                        </button>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>
<script>
    import axios from 'axios'
    import Principal from './Principal';
    import { mapGetters } from 'vuex'

    export default {
        mixins: [Principal],
        data() {
            return {
                success: null,
                error: null,
                sessions: []
            }
        },
        created() {
            this.retrieveSessions();
        },
        methods: {
            retrieveSessions: function () {
                let vm = this;
                axios.get('api/account/sessions/')
                    .then(response => {
                        vm.error = null;
                        vm.sessions = response.data;
                    });
            },
            invalidate: function (session) {
                let vm = this;
                axios.delete('api/account/sessions/' + session)
                    .then(() => {
                        vm.error = null;
                        vm.success = 'OK';
                        vm.retrieveSessions();
                    })
                    .catch(error => {
                        vm.success = null;
                        vm.error = 'ERROR';
                    });
            }
        },
        computed: {
            ...mapGetters([
                'account'
            ])
        }
    }
</script>

// generators/client-2/templates/src/main/webapp/app/account/sessions/_sessions.component.ts
import * as angular from 'angular';

import {Component, OnInit, Inject} from '@angular/core';

import { Session } from './session.model';
import { SessionsService } from './sessions.service';

@Component({
    selector: 'sessions',
    templateUrl: 'app/account/sessions/sessions.html'
})
export class SessionsComponent implements OnInit {

    account: any;
    error: string;
    success: string;
    sessions: Session[];
    Principal: any;

    constructor(private sessionsService: SessionsService, @Inject('Principal') Principal) {
        this.Principal = Principal;
    }

    ngOnInit() {
        this.sessionsService.findAll().subscribe(sessions => this.sessions = sessions);

        this.Principal.identity().then(function(account) {
            this.account = account;
        }.bind(this));
    }

    invalidate (series) {
        let vm = this;
        this.sessionsService.delete(encodeURIComponent(series)).subscribe(
            response => {
                if (response.status === 200) {
                    vm.error = null;
                    vm.success = 'OK';
                    this.sessionsService.findAll().subscribe(sessions => this.sessions = sessions);
                } else {
                    vm.success = null;
                    vm.error = 'ERROR';
                }
            });
    }
}

<div>
    <h2 jhi-translate="sessions.title" translate-values="{username: '{{account.login}}'}" *ngIf="account">Active sessions for [<b>{{account.login}}</b>]</h2>

    <div class="alert alert-success" *ngIf="success" jhi-translate="sessions.messages.success">
        <strong>Session invalidated!</strong>
    </div>
    <div class="alert alert-danger" *ngIf="error" jhi-translate="sessions.messages.error">
        <strong>An error has occured!</strong> The session could not be invalidated.
    </div>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th jhi-translate="sessions.table.ipaddress">IP Address</th>
                    <th jhi-translate="sessions.table.useragent">User agent</th>
                    <th jhi-translate="sessions.table.date">Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let session of sessions">
                    <td>{{session.ipAddress}}</td>
                    <td>{{session.userAgent}}</td>
                    <td>{{session.tokenDate | date:'longDate'}}</td>
                    <td>
                        <button type="submit"
                                class="btn btn-primary"
                                (click)="invalidate(session.series)" jhi-translate="sessions.table.button">
                                 Invalidate
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
