// sandbox/admin/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Badge } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT } from 'app/config/constants';
import { languages } from 'app/config/translation';
import { getUser } from './user-management.reducer';
import { IRootState } from 'app/shared/reducers';

export interface IUserManagementDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ login: string }> {}

export const UserManagementDetail = (props: IUserManagementDetailProps) => {
  useEffect(() => {
    props.getUser(props.match.params.login);
  }, []);

  const { user } = props;

  return (
    <div>
      <h2>
        <Translate contentKey="userManagement.detail.title">User</Translate> [<strong>{user.login}</strong>]
      </h2>
      <Row size="md">
        <dl className="jh-entity-details">
          <dt>
            <Translate contentKey="userManagement.login">Login</Translate>
          </dt>
          <dd>
            <span>{user.login}</span>&nbsp;
            {user.activated ? (
              <Badge color="success">
                <Translate contentKey="userManagement.activated">Activated</Translate>
              </Badge>
            ) : (
              <Badge color="danger">
                <Translate contentKey="userManagement.deactivated">Deactivated</Translate>
              </Badge>
            )}
          </dd>
          <dt>
            <Translate contentKey="userManagement.firstName">First Name</Translate>
          </dt>
          <dd>{user.firstName}</dd>
          <dt>
            <Translate contentKey="userManagement.lastName">Last Name</Translate>
          </dt>
          <dd>{user.lastName}</dd>
          <dt>
            <Translate contentKey="userManagement.email">Email</Translate>
          </dt>
          <dd>{user.email}</dd>
          <dt>
            <Translate contentKey="userManagement.langKey">Lang Key</Translate>
          </dt>
          <dd>{user.langKey ? languages[user.langKey].name : undefined}</dd>
          <dt>
            <Translate contentKey="userManagement.createdBy">Created By</Translate>
          </dt>
          <dd>{user.createdBy}</dd>
          <dt>
            <Translate contentKey="userManagement.createdDate">Created Date</Translate>
          </dt>
          <dd>{user.createdDate ? <TextFormat value={user.createdDate} type="date" format={APP_DATE_FORMAT} blankOnInvalid /> : null}</dd>
          <dt>
            <Translate contentKey="userManagement.lastModifiedBy">Last Modified By</Translate>
          </dt>
          <dd>{user.lastModifiedBy}</dd>
          <dt>
            <Translate contentKey="userManagement.lastModifiedDate">Last Modified Date</Translate>
          </dt>
          <dd>
            {user.lastModifiedDate ? (
              <TextFormat value={user.lastModifiedDate} type="date" format={APP_DATE_FORMAT} blankOnInvalid />
            ) : null}
          </dd>
          <dt>
            <Translate contentKey="userManagement.profiles">Profiles</Translate>
          </dt>
          <dd>
            <ul className="list-unstyled">
              {user.authorities
                ? user.authorities.map((authority, i) => (
                    <li key={`user-auth-${i}`}>
                      <Badge color="info">{authority}</Badge>
                    </li>
                  ))
                : null}
            </ul>
          </dd>
        </dl>
      </Row>
      <Button tag={Link} to="/admin/user-management" replace color="info">
        <FontAwesomeIcon icon="arrow-left" />{' '}
        <span className="d-none d-md-inline">
          <Translate contentKey="entity.action.back">Back</Translate>
        </span>
      </Button>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  user: storeState.userManagement.user,
});

const mapDispatchToProps = { getUser };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(UserManagementDetail);

// gateway/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';
import SharedModule from 'app/shared/shared.module';

import { User } from '../user-management.model';

@Component({
  selector: 'jhi-user-mgmt-detail',
  templateUrl: './user-management-detail.component.html',
  imports: [RouterModule, SharedModule],
})
export default class UserManagementDetailComponent {
  user = input<User | null>(null);
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (user(); as userRef) {
      <div>
        <h2>
          <span jhiTranslate="userManagement.detail.title">User</span> [<strong>{{ userRef.login }}</strong
          >]
        </h2>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="userManagement.login">Login</span></dt>
          <dd>
            <span>{{ userRef.login }}</span>
            @if (userRef.activated) {
              <span class="badge bg-success" jhiTranslate="userManagement.activated">Activated</span>
            } @else {
              <span class="badge bg-danger" jhiTranslate="userManagement.deactivated">Deactivated</span>
            }
          </dd>

          <dt><span jhiTranslate="userManagement.firstName">First name</span></dt>
          <dd>{{ userRef.firstName }}</dd>

          <dt><span jhiTranslate="userManagement.lastName">Last name</span></dt>
          <dd>{{ userRef.lastName }}</dd>

          <dt><span jhiTranslate="userManagement.email">Email</span></dt>
          <dd>{{ userRef.email }}</dd>

          <dt><span jhiTranslate="userManagement.langKey">Language</span></dt>
          <dd>{{ userRef.langKey }}</dd>

          <dt><span jhiTranslate="userManagement.createdBy">Created by</span></dt>
          <dd>{{ userRef.createdBy }}</dd>

          <dt><span jhiTranslate="userManagement.createdDate">Created date</span></dt>
          <dd>{{ userRef.createdDate | date: 'dd/MM/yy HH:mm' }}</dd>

          <dt><span jhiTranslate="userManagement.lastModifiedBy">Modified by</span></dt>
          <dd>{{ userRef.lastModifiedBy }}</dd>

          <dt><span jhiTranslate="userManagement.lastModifiedDate">Modified date</span></dt>
          <dd>{{ userRef.lastModifiedDate | date: 'dd/MM/yy HH:mm' }}</dd>

          <dt><span jhiTranslate="userManagement.profiles">Profiles</span></dt>
          <dd>
            <ul class="list-unstyled">
              @for (authority of userRef.authorities; track $index) {
                <li>
                  <span class="badge bg-info">{{ authority }}</span>
                </li>
              }
            </ul>
          </dd>
        </dl>

        <button type="submit" routerLink="../../" class="btn btn-info">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>
      </div>
    }
  </div>
</div>
