// generators/client-2/templates/src/main/webapp/app/account/register/_register.component.ts
import {Component, OnInit, Inject, Renderer, ElementRef} from '@angular/core';

@Component({
    selector: '<%=jhiPrefix%>-register',
    templateUrl: 'app/account/register/register.html'
})
export class RegisterComponent implements OnInit {

    confirmPassword: string;
    doNotMatch: string;
    error: string;
    errorEmailExists: string;
    errorUserExists: string;
    login: Function;
    registerAccount: any;
    success: boolean;

    constructor(
            @Inject('$translate') private $translate,
            @Inject('Auth') private auth,
            @Inject('LoginService') private loginService,
            private elementRef: ElementRef,
            private renderer: Renderer) {
        this.login = loginService.open;
    }

    ngOnInit() {
        this.success = false;
        this.registerAccount = {};
    }

    ngAfterViewInit() {
        this.renderer.invokeElementMethod(this.elementRef.nativeElement.querySelector('#login'), 'focus', []);
    }

    register() {
        if (this.registerAccount.password !== this.confirmPassword) {
            this.doNotMatch = 'ERROR';
        } else {
            this.registerAccount.langKey = <% if (enableTranslation){ %>this.$translate.use()<% }else {%> 'en' <% } %>;
            this.doNotMatch = null;
            this.error = null;
            this.errorUserExists = null;
            this.errorEmailExists = null;

            this.auth.createAccount(this.registerAccount).then(() => {
                this.success = true;
            }).catch((response) => {
                this.success = null;
                if (response.status === 400 && response.data === 'login already in use') {
                    this.errorUserExists = 'ERROR';
                } else if (response.status === 400 && response.data === 'e-mail address already in use') {
                    this.errorEmailExists = 'ERROR';
                } else {
                    this.error = 'ERROR';
                }
            });
        }
    }
}

<div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1 translate="register.title">Registration</h1>

            <div class="alert alert-success" *ngIf="success" translate="register.messages.success">
                <strong>Registration saved!</strong> Please check your email for confirmation.
            </div>

            <div class="alert alert-danger" *ngIf="error" translate="register.messages.error.fail">
                <strong>Registration failed!</strong> Please try again later.
            </div>

            <div class="alert alert-danger" *ngIf="errorUserExists" translate="register.messages.error.userexists">
                <strong>Login name already registered!</strong> Please choose another one.
            </div>

            <div class="alert alert-danger" *ngIf="errorEmailExists" translate="register.messages.error.emailexists">
                <strong>E-mail is already in use!</strong> Please choose another one.
            </div>

            <div class="alert alert-danger" *ngIf="doNotMatch" translate="global.messages.error.dontmatch">
                The password and its confirmation do not match!
            </div>
        </div>
        <%_ if (enableSocialSignIn) { _%>
        <div class="col-md-4 col-md-offset-2">
        <%_ } else { _%>
        <div class="col-md-8 col-md-offset-2">
        <%_ } _%>
            <form name="form" role="form" (ngSubmit)="register()" #registerForm="ngForm">
                <div class="form-group">
                    <label class="control-label" for="login" translate="global.form.username">Username</label>
                    <input type="text" class="form-control" [(ngModel)]="registerAccount.login" id="login" name="login" #login="ngModel" placeholder="{{'global.form.username.placeholder' | translate}}"
                            required minlength="1" maxlength="50" pattern="^[_'.@A-Za-z0-9-]*$">
                    <div *ngIf="login.dirty && login.invalid">
                        <p class="help-block" *ngIf="login.errors.required" translate="register.messages.validate.login.required">
                            Your username is required.
                        </p>
                        <p class="help-block" *ngIf="login.errors.minlength"
                                translate="register.messages.validate.login.minlength">
                            Your username is required to be at least 1 character.
                        </p>
                        <p class="help-block" *ngIf="login.errors.maxlength"
                                translate="register.messages.validate.login.maxlength">
                            Your username cannot be longer than 50 characters.
                        </p>
                        <p class="help-block" *ngIf="login.errors.pattern"
                               translate="register.messages.validate.login.pattern">
                            Your username can only contain lower-case letters and digits.
                        </p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="email" translate="global.form.email">E-mail</label>
                    <input type="email" class="form-control" id="email" name="email" #email="ngModel" placeholder="{{'global.form.email.placeholder' | translate}}"
                            [(ngModel)]="registerAccount.email" minlength=5 maxlength=100 required>
                    <div *ngIf="email.dirty && email.invalid">
                        <p class="help-block" *ngIf="email.errors.required"
                                translate="global.messages.validate.email.required">
                            Your e-mail is required.
                        </p>
                        <p class="help-block" *ngIf="email.errors.invalid"
                               translate="global.messages.validate.email.invalid">
                            Your e-mail is invalid.
                        </p>
                        <p class="help-block" *ngIf="email.errors.minlength"
                               translate="global.messages.validate.email.minlength">
                            Your e-mail is required to be at least 5 characters.
                        </p>
                        <p class="help-block" *ngIf="email.errors.maxlength"
                               translate="global.messages.validate.email.maxlength">
                            Your e-mail cannot be longer than 100 characters.
                        </p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="password" translate="global.form.newpassword">New password</label>
                    <input type="password" class="form-control" id="password" name="password" #password="ngModel" placeholder="{{'global.form.newpassword.placeholder' | translate}}"
                            [(ngModel)]="registerAccount.password" minlength=4 maxlength=50 required>
                    <div *ngIf="password.dirty && password.invalid">
                        <p class="help-block" *ngIf="password.errors.required"
                                translate="global.messages.validate.newpassword.required">
                            Your password is required.
                        </p>
                        <p class="help-block" *ngIf="password.errors.minlength"
                                translate="global.messages.validate.newpassword.minlength">
                            Your password is required to be at least 4 characters.
                        </p>
                        <p class="help-block" *ngIf="password.errors.maxlength"
                                translate="global.messages.validate.newpassword.maxlength">
                            Your password cannot be longer than 50 characters.
                        </p>
                    </div>
                    <password-strength-bar password-to-check="registerAccount.password"></password-strength-bar>
                </div>
                <div class="form-group">
                    <label class="control-label" for="confirmPassword" translate="global.form.confirmpassword">New password confirmation</label>
                    <input type="password" class="form-control" id="confirmPassword" name="confirmPassword" #confirmPasswordInput="ngModel" placeholder="{{'global.form.confirmpassword.placeholder' | translate}}"
                            [(ngModel)]="confirmPassword" minlength=4 maxlength=50 required>
                    <div *ngIf="confirmPasswordInput.dirty && confirmPasswordInput.invalid">
                        <p class="help-block" *ngIf="confirmPasswordInput.errors.required"
                               translate="global.messages.validate.confirmpassword.required">
                            Your confirmation password is required.
                        </p>
                        <p class="help-block" *ngIf="confirmPasswordInput.errors.minlength"
                              translate="global.messages.validate.confirmpassword.minlength">
                            Your confirmation password is required to be at least 4 characters.
                        </p>
                        <p class="help-block" *ngIf="confirmPasswordInput.errors.maxlength"
                               translate="global.messages.validate.confirmpassword.maxlength">
                            Your confirmation password cannot be longer than 50 characters.
                        </p>
                    </div>
                </div>

                <button type="submit" [disabled]="registerForm.form.invalid" class="btn btn-primary" translate="register.form.button">Register</button>
            </form>
            <p></p>
            <div class="alert alert-warning">
                <span jhi-translate="global.messages.info.authenticated.prefix">If you want to </span>
                <a class="alert-link" (click)="openLogin()" jhi-translate="global.messages.info.authenticated.link">sign in</a><span jhi-translate="global.messages.info.authenticated.suffix">, you can try the default accounts:<br/>- Administrator (login="admin" and password="admin") <br/>- User (login="user" and password="user").</span>
            </div>
        </div>
        <%_ if (enableSocialSignIn) { _%>
        <div class="col-md-4">
            <br/>
            <jh-social provider="google"></jh-social>
            <jh-social provider="facebook"></jh-social>
            <jh-social provider="twitter"></jh-social>
            <!-- jhipster-needle-add-social-button -->
        </div>
        <%_ } _%>
    </div>
</div>

// generators/client/templates/webapp/app/components/account/Register.vue
<template>
    <div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h1 v-text="$t('register.title')">Registration</h1>

                <div class="alert alert-success" v-if="success" v-html="$t('register.messages.success')">
                    <strong>Registration saved!</strong> Please check your email for confirmation.
                </div>

                <div class="alert alert-danger" v-if="error" v-html="$t('register.messages.error.fail')">
                    <strong>Registration failed!</strong> Please try again later.
                </div>

                <div class="alert alert-danger" v-if="errorUserExists" v-html="$t('register.messages.error.userexists')">
                    <strong>Login name already registered!</strong> Please choose another one.
                </div>

                <div class="alert alert-danger" v-if="errorEmailExists" v-html="$t('register.messages.error.emailexists')">
                    <strong>Email is already in use!</strong> Please choose another one.
                </div>

                <div class="alert alert-danger" v-if="doNotMatch" v-text="$t('global.messages.error.dontmatch')">
                    The password and its confirmation do not match!
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form name="registerForm" role="form" v-on:submit.prevent="register()" v-if="!success" no-validate>
                    <div class="form-group">
                        <label class="form-control-label" for="login" v-text="$t('global.form.username')">Username</label>
                        <input type="text" class="form-control" v-model="$v.registerAccount.login.$model" id="login" name="login"
                               :class="{'valid': !$v.registerAccount.login.$invalid, 'invalid': $v.registerAccount.login.$invalid }"
                               required minlength="1" maxlength="50" pattern="^[_.@A-Za-z0-9-]*$" v-bind:placeholder="$t('global.form.username-placeholder')">
                        <div v-if="$v.registerAccount.login.$anyDirty && $v.registerAccount.login.$invalid">
                            <small class="form-text text-danger" v-if="!$v.registerAccount.login.required"
                                   v-text="$t('register.messages.validate.login.required')">
                                Your username is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.registerAccount.login.minLength"
                                   v-text="$t('register.messages.validate.login.minlength')">
                                Your username is required to be at least 1 character.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.registerAccount.login.maxLength"
                                   v-text="$t('register.messages.validate.login.maxlength')">
                                Your username cannot be longer than 50 characters.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.registerAccount.login.pattern"
                                   v-text="$t('register.messages.validate.login.pattern')">
                                Your username can only contain letters and digits.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="email" v-text="$t('global.form.email')">Email</label>
                        <input type="email" class="form-control" id="email" name="email"
                               :class="{'valid': !$v.registerAccount.email.$invalid, 'invalid': $v.registerAccount.email.$invalid }"
                               v-model="$v.registerAccount.email.$model" minlength=5 maxlength=254 email required  v-bind:placeholder="$t('global.form.email-placeholder')">
                        <div v-if="$v.registerAccount.email.$anyDirty && $v.registerAccount.email.$invalid">
                            <small class="form-text text-danger" v-if="!$v.registerAccount.email.required"
                                   v-text="$t('global.messages.validate.email.required')">
                                Your email is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.registerAccount.email.email"
                                   v-text="$t('global.messages.validate.email.invalid')">
                                Your email is invalid.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.registerAccount.email.minLength"
                                   v-text="$t('global.messages.validate.email.minlength')">
                                Your email is required to be at least 5 characters.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.registerAccount.email.maxLength"
                                   v-text="$t('global.messages.validate.email.maxlength')">
                                Your email cannot be longer than 100 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="password" v-text="$t('global.form.newpassword')">New password</label>
                        <input type="password" class="form-control" id="password" name="password"
                               :class="{'valid': !$v.registerAccount.password.$invalid, 'invalid': $v.registerAccount.password.$invalid }"
                               v-model="$v.registerAccount.password.$model" minlength=4 maxlength=50 required  v-bind:placeholder="$t('global.form.newpassword-placeholder')">
                        <div v-if="$v.registerAccount.password.$anyDirty && $v.registerAccount.password.$invalid">
                            <small class="form-text text-danger" v-if="!$v.registerAccount.password.required"
                                   v-text="$t('global.messages.validate.newpassword.required')">
                                Your password is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.registerAccount.password.minLength"
                                   v-text="$t('global.messages.validate.newpassword.minlength')">
                                Your password is required to be at least 4 characters.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.registerAccount.password.maxLength"
                                   v-text="$t('global.messages.validate.newpassword.maxlength')">
                                Your password cannot be longer than 50 characters.
                            </small>
                        </div>
                        <!--<jhi-password-strength-bar [passwordToCheck]="registerAccount.password"></jhi-password-strength-bar>-->
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="confirmPassword" v-text="$t('global.form.confirmpassword')">New password confirmation</label>
                        <input type="password" class="form-control" id="confirmPassword" name="confirmPasswordInput"
                               :class="{'valid': !$v.confirmPassword.$invalid, 'invalid': $v.confirmPassword.$invalid }"
                               v-model="$v.confirmPassword.$model" minlength=4 maxlength=50 required  v-bind:placeholder="$t('global.form.confirmpassword-placeholder')">
                        <div v-if="$v.confirmPassword.$dirty && $v.confirmPassword.$invalid">
                            <small class="form-text text-danger" v-if="!$v.confirmPassword.required"
                                   v-text="$t('global.messages.validate.confirmpassword.required')">
                                Your confirmation password is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.confirmPassword.minLength"
                                   v-text="$t('global.messages.validate.confirmpassword.minlength')">
                                Your confirmation password is required to be at least 4 characters.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.confirmPassword.maxLength"
                                   v-text="$t('global.messages.validate.confirmpassword.maxlength')">
                                Your confirmation password cannot be longer than 50 characters.
                            </small>
                        </div>
                    </div>

                    <button type="submit" :disabled="$v.registerAccount.$invalid || $v.confirmPassword.$invalid" class="btn btn-primary" v-text="$t('register.form.button')">Register</button>
                </form>
                <p></p>
                <div class="alert alert-warning">
                    <span v-text="$t('global.messages.info.authenticated.prefix')">If you want to </span>
                    <a class="alert-link" v-on:click="openLogin()" v-text="$t('global.messages.info.authenticated.link')">sign in</a><span v-html="$t('global.messages.info.authenticated.suffix')">, you can try the default accounts:<br/>- Administrator (login="admin" and password="admin") <br/>- User (login="user" and password="user").</span>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    import RegisterService from './RegisterService'
    import LoginModalService from './LoginModalService'
    import { required, minLength, maxLength, helpers, email } from 'vuelidate/lib/validators'
    import {EMAIL_ALREADY_USED_TYPE, LOGIN_ALREADY_USED_TYPE} from "../../constants";

    const loginPattern = helpers.regex('alpha', /^[_.@A-Za-z0-9-]*$/);

    export default {
        name: 'Register',
        mixins: [RegisterService, LoginModalService],
        data () {
            return {
                confirmPassword: undefined,
                doNotMatch: undefined,
                error: undefined,
                errorEmailExists: undefined,
                errorUserExists: undefined,
                registerAccount: {
                    login: undefined,
                    email: undefined,
                    password: undefined
                },
                success: false
            }
        },
        validations: {
            registerAccount: {
                login: {
                    required,
                    minLength: minLength(1),
                    maxLength: maxLength(50),
                    pattern: loginPattern
                },
                email: {
                    required,
                    minLength: minLength(5),
                    maxLength: maxLength(254),
                    email
                },
                password: {
                    required,
                    minLength: minLength(4),
                    maxLength: maxLength(254),
                }
            },
            confirmPassword: {
                required,
                minLength: minLength(4),
                maxLength: maxLength(254),
            }
        },
        methods: {
            register: function () {
                if (this.registerAccount.password !== this.confirmPassword) {
                    this.doNotMatch = 'ERROR';
                } else {
                    this.doNotMatch = null;
                    this.error = null;
                    this.errorUserExists = null;
                    this.errorEmailExists = null;
                    //this.languageService.getCurrent().then(key => {
                        this.registerAccount.langKey = 'FR';
                        this.processRegistration(this.registerAccount).then(response => {
                            this.success = true;
                        })
                        .catch(error  => {
                            this.success = null;
                            if (error.response.status === 400 && error.response.data.type === LOGIN_ALREADY_USED_TYPE) {
                                this.errorUserExists = 'ERROR';
                            } else if (error.response.status === 400 && error.response.data.type === EMAIL_ALREADY_USED_TYPE) {
                                this.errorEmailExists = 'ERROR';
                            } else {
                                this.error = 'ERROR';
                            }
                        });
                    //});
                }
            }
        }
    }
</script>

<style scoped>

</style>
