// generators/client/templates/angular/src/main/webapp/app/account/sessions/_sessions.component.ts
<%#
 Copyright 2013-2017 the original author or authors.

 This file is part of the JHipster project, see https://jhipster.github.io/
 for more information.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-%>
import { Component, OnInit } from '@angular/core';

import { Session } from './session.model';
import { SessionsService } from './sessions.service';
import { Principal } from '../../shared';

@Component({
    selector: '<%=jhiPrefix%>-sessions',
    templateUrl: './sessions.component.html'
})
export class SessionsComponent implements OnInit {

    account: any;
    error: string;
    success: string;
    sessions: Session[];

    constructor(
        private sessionsService: SessionsService,
        private principal: Principal
    ) {
    }

    ngOnInit() {
        this.sessionsService.findAll().subscribe((sessions) => this.sessions = sessions);

        this.principal.identity().then((account) => {
            this.account = account;
        });
    }

    invalidate(series) {
        this.sessionsService.delete(encodeURIComponent(series)).subscribe(
            (response) => {
                if (response.status === 200) {
                    this.error = null;
                    this.success = 'OK';
                    this.sessionsService.findAll().subscribe((sessions) => this.sessions = sessions);
                } else {
                    this.success = null;
                    this.error = 'ERROR';
                }
            });
    }
}

<%#
 Copyright 2013-2017 the original author or authors from the JHipster project.

 This file is part of the JHipster project, see https://jhipster.github.io/
 for more information.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-%>
<div>
    <h2 jhiTranslate="sessions.title" translateValues="{username: '{{account.login}}'}" *ngIf="account">Active sessions for [<b>{{account.login}}</b>]</h2>

    <div class="alert alert-success" *ngIf="success" jhiTranslate="sessions.messages.success">
        <strong>Session invalidated!</strong>
    </div>
    <div class="alert alert-danger" *ngIf="error" jhiTranslate="sessions.messages.error">
        <strong>An error has occured!</strong> The session could not be invalidated.
    </div>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th jhiTranslate="sessions.table.ipaddress">IP Address</th>
                    <th jhiTranslate="sessions.table.useragent">User agent</th>
                    <th jhiTranslate="sessions.table.date">Date</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let session of sessions">
                    <td>{{session.ipAddress}}</td>
                    <td>{{session.userAgent}}</td>
                    <td>{{session.tokenDate | date:'longDate'}}</td>
                    <td>
                        <button type="submit"
                                class="btn btn-primary"
                                (click)="invalidate(session.series)" jhiTranslate="sessions.table.button">
                                 Invalidate
                        </button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

// generators/client/templates/webapp/app/components/account/Sessions.vue
<template>
    <div>
        <h2 v-if="account"><span v-text="$t('sessions.title')">Active sessions for </span> [<b>{{account.login}}</b>]</h2>

        <div class="alert alert-success" v-if="success" v-html="$t('sessions.messages.success')">
            <strong>Session invalidated!</strong>
        </div>
        <div class="alert alert-danger" v-if="error" v-html="$t('sessions.messages.error')">
            <strong>An error has occured!</strong> The session could not be invalidated.
        </div>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-text="$t('sessions.table.ipaddress')">IP Address</th>
                    <th v-text="$t('sessions.table.useragent')">User agent</th>
                    <th v-text="$t('sessions.table.date')">Date</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="session in sessions">
                    <td>{{session.ipAddress}}</td>
                    <td>{{session.userAgent}}</td>
                    <td>{{session.tokenDate}}</td>
                    <td>
                        <button type="submit"
                                class="btn btn-primary"
                                v-on:click="invalidate(session.series)" v-text="$t('sessions.table.button')">
                            Invalidate
                        </button>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</template>
<script>
    import axios from 'axios'
    import {SERVER_API_URL} from "../../constants";
    import Principal from './Principal';
    import { mapGetters } from 'vuex'

    export default {
        mixins: [Principal],
        data() {
            return {
                success: null,
                error: null,
                sessions: []
            }
        },
        created() {
            this.retrieveSessions();
        },
        methods: {
            retrieveSessions: function () {
                let vm = this;
                axios.get(SERVER_API_URL + 'api/account/sessions/')
                    .then(response => {
                        vm.error = null;
                        vm.sessions = response.data;
                    });
            },
            invalidate: function (session) {
                let vm = this;
                axios.delete(SERVER_API_URL + 'api/account/sessions/' + session)
                    .then(() => {
                        vm.error = null;
                        vm.success = 'OK';
                        vm.retrieveSessions();
                    })
                    .catch(error => {
                        vm.success = null;
                        vm.error = 'ERROR';
                    });
            }
        },
        computed: {
            ...mapGetters([
                'account'
            ])
        }
    }
</script>
