// generators/client/templates/react/src/main/webapp/app/modules/administration/metrics/metrics.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { hashHistory } from 'react-router';
import LinearProgress from 'material-ui/LinearProgress';
import RaisedButton from 'material-ui/RaisedButton';
import FlatButton from 'material-ui/FlatButton';
import { Table, TableBody, TableHeader, TableHeaderColumn, TableRow, TableRowColumn } from 'material-ui/Table';
import { NavigationRefresh, ImageRemoveRedEye } from 'material-ui/svg-icons';
import Translate from 'react-translate-component';
import { systemMetrics, systemThreadDump } from '../../../reducers/administration';

export class MetricsPage extends Component {

  constructor(props) {
    super(props);
    this.getMetrics = this.getMetrics.bind(this);
    this.getStats = this.getStats.bind(this);
    this.getThreadDump = this.getThreadDump.bind(this);
  }

  componentDidMount() {
    this.props.systemMetrics();
  }

  getMetrics() {
    if (!this.props.isFetching) {
      this.props.systemMetrics();
    }
  }

  getThreadDump() {
    this.props.systemThreadDump();
    hashHistory.push('/admin/metrics-detail');
  }

  getStats(metrics) {
    const stat = {
      servicesStats: {},
      cachesStats: {}
    };
    if (!this.props.isFetching && metrics) {
      Object.keys(metrics.timers).forEach((key, indexNm) => {
        if (key.indexOf('web.rest') !== -1 || key.indexOf('service') !== -1) {
          stat.servicesStats[key] = metrics.timers[key];
        }
        if (key.indexOf('net.sf.ehcache.Cache') !== -1) {
          // remove gets or puts
          const index = key.lastIndexOf('.');
          const newKey = key.substr(0, index);
          // Keep the name of the domain
          stat.cachesStats[newKey] = {
            name: newKey,
            value: metrics.timers[key]
          };
        }
      });
      return stat;
    }
  }

  render() {
    const showCheckboxes = false;
    const { metrics, isFetching } = this.props;
    const data = metrics || {};
    const { servicesStats, cachesStats } = this.getStats(data);
    return (
      <div className="well">
        <div>
          <h2 translate="metrics.title">Application Metrics</h2>
          <p>
            <RaisedButton
              label={<Translate content="metrics.refresh.button" />}
              onClick={() => this.getMetrics()} primary
              disabled={isFetching} icon={<NavigationRefresh />}
            />
          </p>
          FIX ME Coloring the progressbar
          <hr />
          <div className="row">
            <div className="col-sm-12">
              <h3>JVM Metrics</h3>
              <div className="row">
                <div className="col-md-4">
                  <b>Memory</b>
                  <p>
                    <span>Total Memory</span>
                    ({metrics.gauges['jvm.memory.total.used'].value / 1000000 || 0}M / {metrics.gauges['jvm.memory.total.max'].value / 1000000 || 0}M)
                  </p>
                  <LinearProgress
                    mode="determinate"
                    value={metrics.gauges['jvm.memory.total.used'].value}
                    min="0"
                    max={metrics.gauges['jvm.memory.total.max'].value}
                  />
                  <span>{((metrics.gauges['jvm.memory.total.used'].value * 100) / metrics.gauges['jvm.memory.total.max'].value) || 0}%</span>

                  <p>
                    <span>Heap Memory</span>
                    ({metrics.gauges['jvm.memory.heap.used'].value / 1000000 || 0}M / {metrics.gauges['jvm.memory.heap.max'].value / 1000000 || 0}M)
                  </p>
                  <LinearProgress
                    mode="determinate"
                    min="0"
                    max={metrics.gauges['jvm.memory.heap.max'].value}
                    value={metrics.gauges['jvm.memory.heap.used'].value}
                  />
                  <span>{((metrics.gauges['jvm.memory.heap.used'].value * 100) / metrics.gauges['jvm.memory.heap.max'].value) || 0}%</span>

                  <p>
                    <span>Non-Heap Memory</span>
                    ({metrics.gauges['jvm.memory.non-heap.used'].value / 1000000 || 0}M / {metrics.gauges['jvm.memory.non-heap.committed'].value / 1000000 || 0}M)
                  </p>
                  <LinearProgress
                    mode="determinate"
                    min="0"
                    max={metrics.gauges['jvm.memory.non-heap.committed'].value}
                    value={metrics.gauges['jvm.memory.non-heap.used'].value}
                  />
                  <span>{((metrics.gauges['jvm.memory.non-heap.used'].value * 100) / metrics.gauges['jvm.memory.non-heap.committed'].value) || 0}%</span>
                </div>
                <div className="col-md-4">
                  <b>Threads</b> (Total: {metrics.gauges['jvm.threads.count'].value})
                  <FlatButton
                    icon={<ImageRemoveRedEye />}
                    onClick={() => this.getThreadDump()}
                  />
                  <p><span>Runnable</span> {metrics.gauges['jvm.threads.runnable.count'].value}</p>
                  <LinearProgress mode="determinate" min="0" value={metrics.gauges['jvm.threads.runnable.count'].value} max={metrics.gauges['jvm.threads.count'].value} />
                  <span>{((metrics.gauges['jvm.threads.runnable.count'].value * 100) / metrics.gauges['jvm.threads.count'].value) || 0}%</span>

                  <p><span>Timed Waiting</span> ({metrics.gauges['jvm.threads.timed_waiting.count'].value})</p>
                  <LinearProgress mode="determinate" min="0" value={metrics.gauges['jvm.threads.timed_waiting.count'].value} max={metrics.gauges['jvm.threads.count'].value} />
                  <span>{((metrics.gauges['jvm.threads.timed_waiting.count'].value * 100) / metrics.gauges['jvm.threads.count'].value) || 0}%</span>

                  <p><span>Waiting</span> ({metrics.gauges['jvm.threads.waiting.count'].value})</p>
                  <LinearProgress mode="determinate" min="0" value={metrics.gauges['jvm.threads.waiting.count'].value} max={metrics.gauges['jvm.threads.count'].value} />
                  <span>{((metrics.gauges['jvm.threads.waiting.count'].value * 100) / metrics.gauges['jvm.threads.count'].value) || 0}%</span>

                  <p><span>Blocked</span> ({metrics.gauges['jvm.threads.blocked.count'].value})</p>
                  <LinearProgress mode="determinate" min="0" value={metrics.gauges['jvm.threads.blocked.count'].value} max={metrics.gauges['jvm.threads.count'].value} />
                  <span>{((metrics.gauges['jvm.threads.blocked.count'].value * 100) / metrics.gauges['jvm.threads.count'].value) || 0}%</span>
                </div>
                <div className="col-md-4">
                  <b>Garbage collections</b>
                  <div className="row">
                    <div className="col-md-9">Mark Sweep count</div>
                    <div className="col-md-3 text-right">{metrics.gauges['jvm.garbage.PS-MarkSweep.count'].value}</div>
                  </div>
                  <div className="row">
                    <div className="col-md-9">Mark Sweep time</div>
                    <div className="col-md-3 text-right">{metrics.gauges['jvm.garbage.PS-MarkSweep.time'].value}ms</div>
                  </div>
                  <div className="row">
                    <div className="col-md-9">Scavenge count</div>
                    <div className="col-md-3 text-right">{metrics.gauges['jvm.garbage.PS-Scavenge.count'].value}</div>
                  </div>
                  <div className="row">
                    <div className="col-md-9">Scavenge time</div>
                    <div className="col-md-3 text-right">{metrics.gauges['jvm.garbage.PS-Scavenge.time'].value}ms</div>
                  </div>
                </div>
              </div>
              <div className="row">
                <div className="col-sm-12">
                  <h3>HTTP requests (events per second)</h3>
                  <p>
                    <span>Active requests</span>
                    <b>{metrics.counters['com.codahale.metrics.servlet.InstrumentedFilter.activeRequests'].count || 0}</b> -
                    <span>Total requests</span> <b>{metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count || 0}</b>
                  </p>
                  <Table>
                    <TableHeader
                      displaySelectAll={showCheckboxes}
                      adjustForCheckbox={showCheckboxes}
                    >
                      <TableRow>
                        <TableHeaderColumn>Code</TableHeaderColumn>
                        <TableHeaderColumn>Count</TableHeaderColumn>
                        <TableHeaderColumn>Mean</TableHeaderColumn>
                        <TableHeaderColumn><span>Average</span> (1 min)</TableHeaderColumn>
                        <TableHeaderColumn><span>Average</span> (5 min)</TableHeaderColumn>
                        <TableHeaderColumn><span>Average</span> (15 min)</TableHeaderColumn>
                      </TableRow>
                    </TableHeader>
                    <TableBody displayRowCheckbox={showCheckboxes}>
                      <TableRow key={0}>
                        <TableRowColumn>OK</TableRowColumn>
                        <TableRowColumn>
                          <LinearProgress
                            mode="determinate"
                            min="0"
                            max={metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count}
                            value={metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].count}
                          />
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].mean_rate || 2}
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m1_rate || 2}
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m5_rate || 2}
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m15_rate || 2}
                        </TableRowColumn>
                      </TableRow>
                      <TableRow key={1}>
                        <TableRowColumn>Not Found</TableRowColumn>
                        <TableRowColumn>
                          <LinearProgress
                            mode="determinate"
                            min="0"
                            max={metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count}
                            value={metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].count}
                          />
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].mean_rate || 2}
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m1_rate || 2}
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m5_rate || 2}
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m15_rate || 2}
                        </TableRowColumn>
                      </TableRow>
                      <TableRow key={2}>
                        <TableRowColumn>Server Error</TableRowColumn>
                        <TableRowColumn>
                          <LinearProgress
                            mode="determinate"
                            min="0"
                            max={metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count}
                            value={metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].count}
                          />
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].mean_rate || 2}
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m1_rate || 2}
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m5_rate || 2}
                        </TableRowColumn>
                        <TableRowColumn>
                          {metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m15_rate || 2}
                        </TableRowColumn>
                      </TableRow>
                    </TableBody>
                  </Table>
                </div>
              </div>

              <div className="row">
                <div className="col-sm-12">
                  <h3>Services statistics (time in millisecond)</h3>
                  <Table>
                    <TableHeader
                      displaySelectAll={showCheckboxes}
                      adjustForCheckbox={showCheckboxes}
                    >
                      <TableRow>
                        <TableHeaderColumn>Name</TableHeaderColumn>
                        <TableHeaderColumn>Count</TableHeaderColumn>
                        <TableHeaderColumn>Mean</TableHeaderColumn>
                        <TableHeaderColumn>Min</TableHeaderColumn>
                        <TableHeaderColumn>p50</TableHeaderColumn>
                        <TableHeaderColumn>p75</TableHeaderColumn>
                        <TableHeaderColumn>p95</TableHeaderColumn>
                        <TableHeaderColumn>p99</TableHeaderColumn>
                        <TableHeaderColumn>Max</TableHeaderColumn>
                      </TableRow>
                    </TableHeader>
                    <TableBody displayRowCheckbox={showCheckboxes}>
                      {Object.keys(servicesStats).map((key, index) => (
                        <TableRow key={key}>
                          <TableRowColumn>{key}</TableRowColumn>
                          <TableRowColumn>{servicesStats[key].count}</TableRowColumn>
                          <TableRowColumn>{servicesStats[key].mean * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{servicesStats[key].min * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{servicesStats[key].p50 * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{servicesStats[key].p75 * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{servicesStats[key].p95 * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{servicesStats[key].p99 * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{servicesStats[key].max * 1000 || 0}</TableRowColumn>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
              <div className="row">
                <div className="col-sm-12">
                  <h3>Ehcache statistics</h3>
                  <Table>
                    <TableHeader
                      displaySelectAll={showCheckboxes}
                      adjustForCheckbox={showCheckboxes}
                    >
                      <TableRow>
                        <TableHeaderColumn>Cache Name</TableHeaderColumn>
                        <TableHeaderColumn>Object</TableHeaderColumn>
                        <TableHeaderColumn>Misses</TableHeaderColumn>
                        <TableHeaderColumn>Eviction Count</TableHeaderColumn>
                      </TableRow>
                    </TableHeader>
                    <TableBody displayRowCheckbox={showCheckboxes}>
                      {Object.keys(cachesStats).map((k, v) => (
                        <TableRow key={k}>
                          <TableRowColumn>{cachesStats.k.name}</TableRowColumn>
                          <TableRowColumn>{metrics.gauges[`${k}.objects`].value}</TableRowColumn>
                          <TableRowColumn>{metrics.gauges[`${k}.hits`].value}</TableRowColumn>
                          <TableRowColumn>{metrics.gauges[`${k}.misses`].value}</TableRowColumn>
                          <TableRowColumn>{metrics.gauges[`${k}.eviction-count`].value}</TableRowColumn>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>
              </div>
              { metrics.gauges['HikariPool-1.pool.TotalConnections'].value > 0 ?
                <div className="row">
                  <div className="col-sm-12">
                    <h3>DataSource statistics (time in millisecond)</h3>
                    <Table>
                      <TableHeader
                        displaySelectAll={showCheckboxes}
                        adjustForCheckbox={showCheckboxes}
                      >
                        <TableRow>
                          <TableHeaderColumn>
                            <span>Usage</span>
                            ({metrics.gauges['HikariPool-1.pool.ActiveConnections'].value} / {metrics.gauges['HikariPool-1.pool.TotalConnections'].value})
                          </TableHeaderColumn>
                          <TableHeaderColumn>Count</TableHeaderColumn>
                          <TableHeaderColumn>Mean</TableHeaderColumn>
                          <TableHeaderColumn>Min</TableHeaderColumn>
                          <TableHeaderColumn>p50</TableHeaderColumn>
                          <TableHeaderColumn>p75</TableHeaderColumn>
                          <TableHeaderColumn>p95</TableHeaderColumn>
                          <TableHeaderColumn>p99</TableHeaderColumn>
                          <TableHeaderColumn>Max</TableHeaderColumn>
                        </TableRow>
                      </TableHeader>
                      <TableBody displayRowCheckbox={showCheckboxes}>
                        <TableRow key="DB">
                          <TableRowColumn>
                            <LinearProgress
                              mode="determinate"
                              min="0"
                              max={metrics.gauges['HikariPool-1.pool.TotalConnections'].value}
                              value={metrics.gauges['HikariPool-1.pool.ActiveConnections'].value}
                            />
                            <span>{((metrics.gauges['HikariPool-1.pool.ActiveConnections'].value * 100) / metrics.gauges['HikariPool-1.pool.TotalConnections'].value) || 0}%</span>
                          </TableRowColumn>
                          <TableRowColumn>{metrics.histograms['HikariPool-1.pool.Usage'].count}</TableRowColumn>
                          <TableRowColumn>{metrics.histograms['HikariPool-1.pool.Usage'].mean * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{metrics.histograms['HikariPool-1.pool.Usage'].min * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{metrics.histograms['HikariPool-1.pool.Usage'].p50 * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{metrics.histograms['HikariPool-1.pool.Usage'].p75 * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{metrics.histograms['HikariPool-1.pool.Usage'].p95 * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{metrics.histograms['HikariPool-1.pool.Usage'].p99 * 1000 || 0}</TableRowColumn>
                          <TableRowColumn>{metrics.histograms['HikariPool-1.pool.Usage'].max * 1000 || 0}</TableRowColumn>
                        </TableRow>
                      </TableBody>
                    </Table>
                  </div>
                </div>
              : null }
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default connect(
  ({ administration }) => ({ metrics: administration.metrics, isFetching: administration.isFetching }),
  { systemMetrics, systemThreadDump }
)(MetricsPage);

// generators/client-2/templates/src/main/webapp/app/admin/metrics/_metrics.component.ts
import { Component, Inject, OnInit, TemplateRef } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { <%=jhiPrefixCapitalized%>MetricsService } from './metrics.service';

@Component({
    selector: '<%=jhiPrefix%>-metrics',
    templateUrl: 'app/admin/metrics/metrics.html',
})
export class <%=jhiPrefixCapitalized%>MetricsMonitoringComponent implements OnInit {
    metrics: any = {};
    cachesStats: any = {};
    servicesStats: any = {};
    updatingMetrics: boolean = true;
    threadDump: any;

    constructor(private modalService: NgbModal, private metricsService:<%=jhiPrefixCapitalized%>MetricsService) {}

    ngOnInit() {
        this.refresh();
    }

    refresh () {
        this.updatingMetrics = true;
        this.metricsService.getMetrics().subscribe((metrics) => {
            this.metrics = metrics;
            this.updatingMetrics = false;
            this.servicesStats = {};
            this.cachesStats = {};
            Object.keys(metrics.timers).forEach((key) => {
                let value = metrics.timers[key];
                if (key.indexOf('web.rest') !== -1 || key.indexOf('service') !== -1) {
                    this.servicesStats[key] = value;
                }
                if (key.indexOf('net.sf.ehcache.Cache') !== -1) {
                    // remove gets or puts
                    let index = key.lastIndexOf('.');
                    let newKey = key.substr(0, index);

                    // Keep the name of the domain
                    index = newKey.lastIndexOf('.');
                    this.cachesStats[newKey] = {
                        'name': newKey.substr(index + 1),
                        'value': value
                    };
                }
            });
        });
    }

    refreshThreadDumpData (metricsModal: TemplateRef<any>) {
        this.metricsService.threadDump().subscribe((data) => {
            this.threadDump = data;
            this.modalService.open(metricsModal, { size: 'lg'}).result.then((result) => {
                console.log(`Closed with: ${result}`);
            }, (reason) => {
                console.log(`Dismissed ${reason}`);
            });
        });
    }

}

<div>
    <h2 jhi-translate="metrics.title">Application Metrics</h2>
    <p>
        <button type="button" class="btn btn-primary" (click)="refresh()"><span class="glyphicon glyphicon-refresh"></span>&nbsp;<span jhi-translate="metrics.refresh.button">Refresh</span></button>
    </p>

    <h3 jhi-translate="metrics.jvm.title">JVM Metrics</h3>
    <div class="row" *ngIf="!updatingMetrics">
        <div class="col-md-4">
            <b jhi-translate="metrics.jvm.memory.title">Memory</b>
            <p><span jhi-translate="metrics.jvm.memory.total">Total Memory</span> ({{metrics.gauges['jvm.memory.total.used'].value / 1000000 | number:'1.0-0'}}M / {{metrics.gauges['jvm.memory.total.max'].value / 1000000 | number:'1.0-0'}}M)</p>
            <ngb-progressbar type="success" [max]="metrics.gauges['jvm.memory.total.max'].value" [value]="metrics.gauges['jvm.memory.total.used'].value" [striped]="true" [animated]="true">
                <span>{{metrics.gauges['jvm.memory.total.used'].value * 100 / metrics.gauges['jvm.memory.total.max'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span jhi-translate="metrics.jvm.memory.heap">Heap Memory</span> ({{metrics.gauges['jvm.memory.heap.used'].value / 1000000 | number:'1.0-0'}}M / {{metrics.gauges['jvm.memory.heap.max'].value / 1000000 | number:'1.0-0'}}M)</p>
            <ngb-progressbar [max]="metrics.gauges['jvm.memory.heap.max'].value" [value]="metrics.gauges['jvm.memory.heap.used'].value" [striped]="true" [animated]="true" type="success">
                <span>{{metrics.gauges['jvm.memory.heap.used'].value * 100 / metrics.gauges['jvm.memory.heap.max'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span jhi-translate="metrics.jvm.memory.nonheap">Non-Heap Memory</span> ({{metrics.gauges['jvm.memory.non-heap.used'].value / 1000000 | number:'1.0-0'}}M / {{metrics.gauges['jvm.memory.non-heap.committed'].value / 1000000 | number:'1.0-0'}}M)</p>
            <ngb-progressbar [max]="metrics.gauges['jvm.memory.non-heap.committed'].value" [value]="metrics.gauges['jvm.memory.non-heap.used'].value" [striped]="true" [animated]="true" type="success">
                <span>{{metrics.gauges['jvm.memory.non-heap.used'].value * 100 / metrics.gauges['jvm.memory.non-heap.committed'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
        </div>
        <div class="col-md-4">
            <b jhi-translate="metrics.jvm.threads.title">Threads</b> (Total: {{metrics.gauges['jvm.threads.count'].value}}) <a class="hand" (click)="refreshThreadDumpData()" data-toggle="modal" data-target="#threadDump"><i class="glyphicon glyphicon-eye-open"></i></a>
            <p><span jhi-translate="metrics.jvm.threads.runnable">Runnable</span> {{metrics.gauges['jvm.threads.runnable.count'].value}}</p>
            <ngb-progressbar [value]="metrics.gauges['jvm.threads.runnable.count'].value" [max]="metrics.gauges['jvm.threads.count'].value" [striped]="true" [animated]="true" type="success">
                <span>{{metrics.gauges['jvm.threads.runnable.count'].value * 100 / metrics.gauges['jvm.threads.count'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span jhi-translate="metrics.jvm.threads.timedwaiting">Timed Waiting</span> ({{metrics.gauges['jvm.threads.timed_waiting.count'].value}})</p>
            <ngb-progressbar [value]="metrics.gauges['jvm.threads.timed_waiting.count'].value" [max]="metrics.gauges['jvm.threads.count'].value" [striped]="true" [animated]="true" type="warning">
                <span>{{metrics.gauges['jvm.threads.timed_waiting.count'].value * 100 / metrics.gauges['jvm.threads.count'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span jhi-translate="metrics.jvm.threads.waiting">Waiting</span> ({{metrics.gauges['jvm.threads.waiting.count'].value}})</p>
            <ngb-progressbar [value]="metrics.gauges['jvm.threads.waiting.count'].value" [max]="metrics.gauges['jvm.threads.count'].value" [striped]="true" [animated]="true" type="warning">
                <span>{{metrics.gauges['jvm.threads.waiting.count'].value * 100 / metrics.gauges['jvm.threads.count'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
            <p><span jhi-translate="metrics.jvm.threads.blocked">Blocked</span> ({{metrics.gauges['jvm.threads.blocked.count'].value}})</p>
            <ngb-progressbar [value]="metrics.gauges['jvm.threads.blocked.count'].value" [max]="metrics.gauges['jvm.threads.count'].value" [striped]="true" [animated]="true" type="success">
                <span>{{metrics.gauges['jvm.threads.blocked.count'].value * 100 / metrics.gauges['jvm.threads.count'].value  | number:'1.0-0'}}%</span>
            </ngb-progressbar>
        </div>
        <div class="col-md-4">
            <b jhi-translate="metrics.jvm.gc.title">Garbage collections</b>
            <div class="row">
                <div class="col-md-9" jhi-translate="metrics.jvm.gc.marksweepcount">Mark Sweep count</div>
                <div class="col-md-3 text-right">{{metrics.gauges['jvm.garbage.PS-MarkSweep.count'].value}}</div>
            </div>
            <div class="row">
                <div class="col-md-9" jhi-translate="metrics.jvm.gc.marksweeptime">Mark Sweep time</div>
                <div class="col-md-3 text-right">{{metrics.gauges['jvm.garbage.PS-MarkSweep.time'].value}}ms</div>
            </div>
            <div class="row">
                <div class="col-md-9" jhi-translate="metrics.jvm.gc.scavengecount">Scavenge count</div>
                <div class="col-md-3 text-right">{{metrics.gauges['jvm.garbage.PS-Scavenge.count'].value}}</div>
            </div>
            <div class="row">
                <div class="col-md-9" jhi-translate="metrics.jvm.gc.scavengetime">Scavenge time</div>
                <div class="col-md-3 text-right">{{metrics.gauges['jvm.garbage.PS-Scavenge.time'].value}}ms</div>
            </div>
        </div>
    </div>
    <div class="well well-lg" *ngIf="updatingMetrics" jhi-translate="metrics.updating">Updating...</div>

    <h3 jhi-translate="metrics.jvm.http.title">HTTP requests (events per second)</h3>
    <p *ngIf="metrics.counters">
        <span jhi-translate="metrics.jvm.http.active">Active requests</span> <b>{{metrics.counters['com.codahale.metrics.servlet.InstrumentedFilter.activeRequests'].count | number:'1.0-0'}}</b> - <span jhi-translate="metrics.jvm.http.total">Total requests</span> <b>{{metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count | number:'1.0-0'}}</b>
    </p>
    <div class="table-responsive" *ngIf="!updatingMetrics">
        <table class="table table-striped">
            <thead>
            <tr>
                <th jhi-translate="metrics.jvm.http.table.code">Code</th>
                <th jhi-translate="metrics.jvm.http.table.count">Count</th>
                <th class="text-right" jhi-translate="metrics.jvm.http.table.mean">Mean</th>
                <th class="text-right"><span jhi-translate="metrics.jvm.http.table.average">Average</span> (1 min)</th>
                <th class="text-right"><span jhi-translate="metrics.jvm.http.table.average">Average</span> (5 min)</th>
                <th class="text-right"><span jhi-translate="metrics.jvm.http.table.average">Average</span> (15 min)</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td jhi-translate="metrics.jvm.http.code.ok">OK</td>
                <td>
                    <ngb-progressbar [max]="metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count" [value]="metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].count" [striped]="true" [animated]="true" type="success">
                        <span>{{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].count}}</span>
                    </ngb-progressbar>
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].mean_rate | number:'1.0-2'}}
                </td>
                <td class="text-right">{{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m1_rate | number:'1.0-2'}}
                </td>
                <td class="text-right">{{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m5_rate | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.ok'].m15_rate | number:'1.0-2'}}
                </td>
            </tr>
            <tr>
                <td jhi-translate="metrics.jvm.http.code.notfound">Not Found</td>
                <td>
                    <ngb-progressbar [max]="metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count" [value]="metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].count" [striped]="true" [animated]="true" type="success">
                        <span>{{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].count}}</span>
                    </ngb-progressbar>
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].mean_rate | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m1_rate | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m5_rate | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.notFound'].m15_rate | number:'1.0-2'}}
                </td>
            </tr>
            <tr>
                <td jhi-translate="metrics.jvm.http.code.servererror">Server error</td>
                <td>
                    <ngb-progressbar [max]="metrics.timers['com.codahale.metrics.servlet.InstrumentedFilter.requests'].count" [value]="metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].count" [striped]="true" [animated]="true" type="success">
                        <span>{{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].count}}</span>
                    </ngb-progressbar>
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].mean_rate | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m1_rate | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m5_rate | number:'1.0-2'}}
                </td>
                <td class="text-right">
                    {{metrics.meters['com.codahale.metrics.servlet.InstrumentedFilter.responseCodes.serverError'].m15_rate | number:'1.0-2'}}
                </td>
            </tr>
            </tbody>
        </table>
    </div>

    <h3 jhi-translate="metrics.servicesstats.title">Services statistics (time in millisecond)</h3>
    <div class="table-responsive" *ngIf="!updatingMetrics">
        <table class="table table-striped">
            <thead>
            <tr>
                <th jhi-translate="metrics.servicesstats.table.name">Service name</th>
                <th class="text-right" jhi-translate="metrics.servicesstats.table.count">Count</th>
                <th class="text-right" jhi-translate="metrics.servicesstats.table.mean">Mean</th>
                <th class="text-right" jhi-translate="metrics.servicesstats.table.min">Min</th>
                <th class="text-right" jhi-translate="metrics.servicesstats.table.p50">p50</th>
                <th class="text-right" jhi-translate="metrics.servicesstats.table.p75">p75</th>
                <th class="text-right" jhi-translate="metrics.servicesstats.table.p95">p95</th>
                <th class="text-right" jhi-translate="metrics.servicesstats.table.p99">p99</th>
                <th class="text-right" jhi-translate="metrics.servicesstats.table.max">Max</th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let entry of servicesStats | keys">
                <td>{{entry.key}}</td>
                <td class="text-right">{{entry.value.count}}</td>
                <td class="text-right">{{entry.value.mean * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.min * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.p50 * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.p75 * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.p95 * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.p99 * 1000 | number:'1.0-0'}}</td>
                <td class="text-right">{{entry.value.max * 1000 | number:'1.0-0'}}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <% if (hibernateCache == 'ehcache') { %>
    <h3 jhi-translate="metrics.ehcache.title">Ehcache statistics</h3>
    <div class="table-responsive" *ngIf="!updatingMetrics">
        <table class="table table-striped">
            <thead>
            <tr>
                <th jhi-translate="metrics.ehcache.cachename">Cache name</th>
                <th class="text-right" jhi-translate="metrics.ehcache.objects">Objects</th>
                <th class="text-right" jhi-translate="metrics.ehcache.hits">Hits</th>
                <th class="text-right" jhi-translate="metrics.ehcache.misses">Misses</th>
                <th class="text-right" jhi-translate="metrics.ehcache.evictioncount">Eviction count</th>
                <th class="text-right" jhi-translate="metrics.ehcache.mean">Mean get time (ms)</th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let entry of cachesStats | keys">
                <td>{{entry.value.name}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.objects'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.hits'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.misses'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.eviction-count'].value}}</td>
                <td class="text-right">{{metrics.gauges[entry.key + '.mean-get-time'].value}}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <% } %>
    <h3 jhi-translate="metrics.datasource.title" *ngIf="metrics.gauges && metrics.gauges['HikariPool-1.pool.TotalConnections'].value > 0">DataSource statistics (time in millisecond)</h3>
    <div class="table-responsive" *ngIf="!updatingMetrics && metrics.gauges && metrics.gauges['HikariPool-1.pool.TotalConnections'].value > 0">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th><span jhi-translate="metrics.datasource.usage">Usage</span> ({{metrics.gauges['HikariPool-1.pool.ActiveConnections'].value}} / {{metrics.gauges['HikariPool-1.pool.TotalConnections'].value}})</th>
                    <th class="text-right" jhi-translate="metrics.datasource.count">Count</th>
                    <th class="text-right" jhi-translate="metrics.datasource.mean">Mean</th>
                    <th class="text-right" jhi-translate="metrics.datasource.min">Min</th>
                    <th class="text-right" jhi-translate="metrics.datasource.p50">p50</th>
                    <th class="text-right" jhi-translate="metrics.datasource.p75">p75</th>
                    <th class="text-right" jhi-translate="metrics.datasource.p95">p95</th>
                    <th class="text-right" jhi-translate="metrics.datasource.p99">p99</th>
                    <th class="text-right" jhi-translate="metrics.datasource.max">Max</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div class="progress progress-striped">
                            <ngb-progressbar [max]="metrics.gauges['HikariPool-1.pool.TotalConnections'].value" [value]="metrics.gauges['HikariPool-1.pool.ActiveConnections'].value" [striped]="true" [animated]="true" type="success">
                                <span>{{metrics.gauges['HikariPool-1.pool.ActiveConnections'].value * 100 / metrics.gauges['HikariPool-1.pool.TotalConnections'].value  | number:'1.0-0'}}%</span>
                            </ngb-progressbar>
                        </div>
                    </td>
                    <td class="text-right">{{metrics.histograms['HikariPool-1.pool.Usage'].count}}</td>
                    <td class="text-right">{{metrics.histograms['HikariPool-1.pool.Usage'].mean | number:'1.0-2'}}</td>
                    <td class="text-right">{{metrics.histograms['HikariPool-1.pool.Usage'].min | number:'1.0-2'}}</td>
                    <td class="text-right">{{metrics.histograms['HikariPool-1.pool.Usage'].p50 | number:'1.0-2'}}</td>
                    <td class="text-right">{{metrics.histograms['HikariPool-1.pool.Usage'].p75 | number:'1.0-2'}}</td>
                    <td class="text-right">{{metrics.histograms['HikariPool-1.pool.Usage'].p95 | number:'1.0-2'}}</td>
                    <td class="text-right">{{metrics.histograms['HikariPool-1.pool.Usage'].p99 | number:'1.0-2'}}</td>
                    <td class="text-right">{{metrics.histograms['HikariPool-1.pool.Usage'].max | number:'1.0-2'}}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
