// generators/client/templates/webapp/app/components/account/Settings.vue
<template>
    <div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <h2 v-if="username"><span v-bind:value="$t('settings.title')">User settings for [<b>{{username}}</b>]</span></h2>

                <div class="alert alert-success" v-if="success" v-html="$t('settings.messages.success')">
                    <strong>Settings saved!</strong>
                </div>

                <!--<jhi-alert-error></jhi-alert-error>-->

                <form name="form" role="form" v-on:submit.prevent="save()" v-if="settingsAccount" novalidate>

                    <div class="form-group">
                        <label class="form-control-label" for="firstName" v-text="$t('settings.form.firstname')">First Name</label>
                        <input type="text" class="form-control" id="firstName" name="firstName" v-bind:placeholder="$t('settings.form[\'firstname.placeholder\']')"
                               :class="{'valid': !$v.settingsAccount.firstName.$invalid, 'invalid': $v.settingsAccount.firstName.$invalid }"
                               v-model="$v.settingsAccount.firstName.$model" minlength=1 maxlength=50 required>
                        <div v-if="$v.settingsAccount.firstName.$anyDirty && $v.settingsAccount.firstName.$invalid">
                            <small class="form-text text-danger"
                                   v-if="!$v.settingsAccount.firstName.required" v-text="$t('settings.messages.validate.firstname.required')">
                                Your first name is required.
                            </small>
                            <small class="form-text text-danger"
                                   v-if="!$v.settingsAccount.firstName.minLength" v-text="$t('settings.messages.validate.firstname.minlength')">
                                Your first name is required to be at least 1 character.
                            </small>
                            <small class="form-text text-danger"
                                   v-if="!$v.settingsAccount.firstName.maxLength" v-text="$t('settings.messages.validate.firstname.maxlength')">
                                Your first name cannot be longer than 50 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="lastName" v-text="$t('settings.form.lastname')">Last Name</label>
                        <input type="text" class="form-control" id="lastName" name="lastName" v-bind:placeholder="$t('settings.form[\'lastname.placeholder\']')"
                               :class="{'valid': !$v.settingsAccount.lastName.$invalid, 'invalid': $v.settingsAccount.lastName.$invalid }"
                               v-model="$v.settingsAccount.lastName.$model" minlength=1 maxlength=50 required>
                        <div v-if="$v.settingsAccount.lastName.$anyDirty && $v.settingsAccount.lastName.$invalid">
                            <small class="form-text text-danger"
                                   v-if="!$v.settingsAccount.lastName.required" v-text="$t('settings.messages.validate.lastname.required')">
                                Your last name is required.
                            </small>
                            <small class="form-text text-danger"
                                   v-if="!$v.settingsAccount.lastName.minLength" v-text="$t('settings.messages.validate.lastname.minlength')">
                                Your last name is required to be at least 1 character.
                            </small>
                            <small class="form-text text-danger"
                                   v-if="!$v.settingsAccount.lastName.maxLength" v-text="$t('settings.messages.validate.lastname.maxlength')">
                                Your last name cannot be longer than 50 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="email" v-text="$t('global.form.email')">Email</label>
                        <input type="email" class="form-control" id="email" name="email" v-bind:placeholder="$t('global.form[\'email.placeholder\']')"
                               :class="{'valid': !$v.settingsAccount.email.$invalid, 'invalid': $v.settingsAccount.email.$invalid }"
                               v-model="$v.settingsAccount.email.$model" minlength="5" maxlength="254" email required>
                        <div v-if="$v.settingsAccount.email.$anyDirty && $v.settingsAccount.email.$invalid">
                            <small class="form-text text-danger" v-if="!$v.settingsAccount.email.required"
                                   v-text="$t('global.messages.validate.email.required')">
                                Your email is required.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.settingsAccount.email.email"
                                   v-text="$t('global.messages.validate.email.invalid')">
                                Your email is invalid.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.settingsAccount.email.minLength"
                                   v-text="$t('global.messages.validate.email.minlength')">
                                Your email is required to be at least 5 characters.
                            </small>
                            <small class="form-text text-danger" v-if="!$v.settingsAccount.email.maxLength"
                                   v-text="$t('global.messages.validate.email.maxlength')">
                                Your email cannot be longer than 100 characters.
                            </small>
                        </div>
                    </div>
                    <div class="form-group" v-if="languages && Object.keys(languages).length > 1">
                        <label for="langKey" v-text="$t('settings.form.language')">Language</label>
                        <select class="form-control" id="langKey" name="langKey" v-model="settingsAccount.langKey">
                            <option v-for="(language, key) in languages" :value="key">{{language.name}}</option>
                        </select>
                    </div>
                    <button type="submit" :disabled="$v.settingsAccount.$invalid" class="btn btn-primary" v-text="$t('settings.form.button')">Save</button>
                </form>
            </div>
        </div>

    </div>
</template>
<script>
    import {email, maxLength, minLength, required} from 'vuelidate/lib/validators'
    import axios from 'axios'
    import Principal from './Principal';
    import LanguageService from '../../locale/LanguageService';

    export default {
        mixins: [Principal, LanguageService],
        data() {
            return {
                success: null,
                error: null
            }
        },
        validations: {
            settingsAccount: {
                firstName: {
                    required,
                    minLength: minLength(1),
                    maxLength: maxLength(50)
                },
                lastName: {
                    required,
                    minLength: minLength(1),
                    maxLength: maxLength(50)
                },
                email: {
                    required,
                    email,
                    minLength: minLength(5),
                    maxLength: maxLength(254)
                }
            }
        },
        methods: {
            save: function () {
                let vm = this;
                axios.post('api/account', this.settingsAccount)
                    .then(() => {
                        vm.error = null;
                        vm.success = "OK";
                        vm.retrieveAccount();
                    })
                    .catch(error => {
                        vm.success = null;
                        vm.error = 'ERROR';
                    });
            }
        },
        computed: {
            settingsAccount() {
                return this.$store.getters.account
            }
        }
    }
</script>

// generators/client-2/templates/src/main/webapp/app/account/settings/_settings.component.ts
import {Component, Inject, OnInit} from '@angular/core';

@Component({
    selector: 'settings',
    templateUrl: 'app/account/settings/settings.html'
})
export class SettingsComponent implements OnInit {
    error: string;
    success: string;
    settingsAccount: any;
    Auth: any;
    Principal: any;
    // <%=jhiPrefixCapitalized%>LanguageService: any;

    constructor(@Inject('$translate') private $translate, @Inject('Auth') Auth, @Inject('Principal') Principal)
    @Inject('<%=jhiPrefixCapitalized%>LanguageService') <%=jhiPrefixCapitalized%>LanguageService) {
        this.Auth = Auth;
        this.Principal = Principal;
        this.<%=jhiPrefixCapitalized%>LanguageService = <%=jhiPrefixCapitalized%>LanguageService;
    }

    ngOnInit () {
        let vm = this;
        this.Principal.identity().then(function(account) {
            vm.settingsAccount = this.copyAccount(account);
        });
    }

    save () {
        let vm = this;
        this.Auth.updateAccount(vm.settingsAccount).then(function() {
            vm.error = null;
            vm.success = 'OK';
            this.Principal.identity(true).then(function(account) {
                vm.settingsAccount = this.copyAccount(account);
            });<% if (enableTranslation){ %>
            this.<%=jhiPrefixCapitalized%>LanguageService.getCurrent().then(function(current) {
                if (vm.settingsAccount.langKey !== current) {
                    this.$translate.use(vm.settingsAccount.langKey);
                }
            });<% } %>
        }).catch(function() {
            vm.success = null;
            vm.error = 'ERROR';
        });
    }

    copyAccount (account) {
        return {
            activated: account.activated,
            email: account.email,
            firstName: account.firstName,
            langKey: account.langKey,
            lastName: account.lastName,
            login: account.login
        };
    }
}

<div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2 translate="settings.title" translate-values="{username: '{{settingsAccount.login}}'}" *ngIf="settingsAccount">User settings for [<b>{{settingsAccount.login}}</b>]</h2>

            <div class="alert alert-success" *ngIf="success" translate="settings.messages.success">
                <strong>Settings saved!</strong>
            </div>

            <jhi-alert-error></jhi-alert-error>

            <form name="form" role="form" (ngSubmit)="save()" #settingsForm="ngForm" *ngIf="settingsAccount" novalidate show-validation>

                <div class="form-group">
                    <label class="control-label" for="firstName" translate="settings.form.firstname">First Name</label>
                    <input type="text" class="form-control" id="firstName" name="firstName" placeholder="{{'settings.form.firstname.placeholder' | translate}}"
                           [(ngModel)]="settingsAccount.firstName" minlength=1 maxlength=50 #firstNameInput="ngModel" required>
                    <div *ngIf="firstNameInput.dirty && firstNameInput.invalid">
                        <p class="help-block"
                           *ngIf="firstNameInput.errors.required" translate="settings.messages.validate.firstname.required">
                            Your first name is required.
                        </p>
                        <p class="help-block"
                           *ngIf="firstNameInput.errors.minlength" translate="settings.messages.validate.firstname.minlength">
                            Your first name is required to be at least 1 character.
                        </p>
                        <p class="help-block"
                           *ngIf="firstNameInput.errors.maxlength" translate="settings.messages.validate.firstname.maxlength">
                            Your first name cannot be longer than 50 characters.
                        </p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="lastName" translate="settings.form.lastname">Last Name</label>
                    <input type="text" class="form-control" id="lastName" name="lastName" placeholder="{{'settings.form.lastname.placeholder' | translate}}"
                           [(ngModel)]="settingsAccount.lastName" minlength=1 maxlength=50 #lastNameInput="ngModel" required>
                    <div *ngIf="lastNameInput.dirty && lastNameInput.invalid">
                        <p class="help-block"
                           *ngIf="lastNameInput.errors.required" translate="settings.messages.validate.lastname.required">
                            Your last name is required.
                        </p>
                        <p class="help-block"
                           *ngIf="lastNameInput.errors.minlength" translate="settings.messages.validate.lastname.minlength">
                            Your last name is required to be at least 1 character.
                        </p>
                        <p class="help-block"
                           *ngIf="lastNameInput.errors.maxlength" translate="settings.messages.validate.lastname.maxlength">
                            Your last name cannot be longer than 50 characters.
                        </p>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label" for="email" translate="global.form.email">E-mail</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="{{'global.form.email.placeholder' | translate}}"
                           [(ngModel)]="settingsAccount.email" minlength=5 maxlength=100 #emailInput="ngModel" required>
                    <div *ngIf="emailInput.dirty && emailInput.invalid">
                        <p class="help-block"
                           *ngIf="emailInput.errors.required" translate="global.messages.validate.email.required">
                            Your e-mail is required.
                        </p>
                        <p class="help-block"
                           *ngIf="emailInput.errors.email" translate="global.messages.validate.email.invalid">
                            Your e-mail is invalid.
                        </p>
                        <p class="help-block"
                           *ngIf="emailInput.errors.minlength" translate="global.messages.validate.email.minlength">
                            Your e-mail is required to be at least 5 characters.
                        </p>
                        <p class="help-block"
                           *ngIf="emailInput.errors.maxlength" translate="global.messages.validate.email.maxlength">
                            Your e-mail cannot be longer than 100 characters.
                        </p>
                    </div>
                </div>
                <%_ if (enableTranslation){ _%>
                <div class="form-group" *ngIf="languages && languages.length > 0">
                    <label for="langKey" translate="settings.form.language">Language</label>
                    <select class="form-control" id="langKey" name="langKey" [(ngModel)]="settingsAccount.langKey">
                        <option *ngFor="let language of languages" [value]="language">{{language | findLanguageFromKey}}</option>
                    </select>
                </div>
                <%_ } _%>
                <button type="submit" [disabled]="settingsForm.form.invalid" class="btn btn-primary" translate="settings.form.button">Save</button>
            </form>
        </div>
    </div>

</div>
