// generators/client/templates/react/src/main/webapp/app/modules/administration/logs/logs.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import Translate from 'react-translate-component';

import { getLoggers, changeLogLevel } from '../../../reducers/administration';

export class LogsPage extends Component {

  constructor(props) {
    super(props);
    this.getLogs = this.getLogs.bind(this);
    this.changeLevel = this.changeLevel.bind(this);
  }

  componentDidMount() {
    this.props.getLoggers();
  }

  getLogs() {
    if (!this.props.isFetching) {
      this.props.getLoggers();
    }
  }

  changeLevel(loggerName, level) {
    this.props.changeLogLevel(loggerName, level);
  }

  render() {
    const { logs, isFetching } = this.props;
    const loggers = logs ? logs.loggers : {};
    return (

      <div className="well ng-scope">
        <div className="table-responsive">
          <h2>Logs</h2>
          <p>There are { loggers.length } loggers.</p>

          <span>Filter</span>
          <input type="text" className="form-control" disabled={isFetching} />

          <table className="table table-condensed table-striped table-bordered" >
            <thead>
              <tr title="click to order">
                <th><span>Name</span></th>
                <th><span>Level</span></th>
              </tr>
            </thead>
            <tbody>
              {
              loggers.map((logger, i) =>
                <tr>
                  <td><small>{logger.name}</small></td>
                  <td>
                    <button disabled={isFetching} onClick={() => this.changeLevel(logger.name, 'TRACE')} className={`btn btn-default btn-xs ${(logger.level == 'TRACE') ? 'btn-danger' : 'btn-default'}`}>TRACE</button>
                    <button disabled={isFetching} onClick={() => this.changeLevel(logger.name, 'DEBUG')} className={`btn btn-default btn-xs ${(logger.level == 'DEBUG') ? 'btn-warning' : 'btn-default'}`}>DEBUG</button>
                    <button disabled={isFetching} onClick={() => this.changeLevel(logger.name, 'INFO')} className={`btn btn-default btn-xs ${(logger.level == 'INFO') ? 'btn-info' : 'btn-default'}`}>INFO</button>
                    <button disabled={isFetching} onClick={() => this.changeLevel(logger.name, 'WARN')} className={`btn btn-default btn-xs ${(logger.level == 'WARN') ? 'btn-success' : 'btn-default'}`}>WARN</button>
                    <button disabled={isFetching} onClick={() => this.changeLevel(logger.name, 'ERROR')} className={`btn btn-default btn-xs ${(logger.level == 'WARN') ? 'btn-primary' : 'btn-default'}`}>ERROR</button>
                  </td>
                </tr>
              )
            }
            </tbody>
          </table>
        </div>
      </div>
    );
  }
}

export default connect(
  ({ administration }) => ({ logs: administration.logs, isFetching: administration.isFetching }),
  { getLoggers, changeLogLevel }
)(LogsPage);

// sandraapp/src/main/webapp/app/admin/logs/logs.component.ts
import { Component, OnInit } from '@angular/core';

import { Log, LoggersResponse, Level } from './log.model';
import { LogsService } from './logs.service';

@Component({
  selector: 'jhi-logs',
  templateUrl: './logs.component.html',
})
export class LogsComponent implements OnInit {
  loggers?: Log[];
  filter = '';
  orderProp = 'name';
  reverse = false;

  constructor(private logsService: LogsService) {}

  ngOnInit(): void {
    this.findAndExtractLoggers();
  }

  changeLevel(name: string, level: Level): void {
    this.logsService.changeLevel(name, level).subscribe(() => this.findAndExtractLoggers());
  }

  private findAndExtractLoggers(): void {
    this.logsService
      .findAll()
      .subscribe(
        (response: LoggersResponse) =>
          (this.loggers = Object.entries(response.loggers).map(([key, logger]) => new Log(key, logger.effectiveLevel)))
      );
  }
}

<div class="table-responsive" *ngIf="loggers">
    <h2 id="logs-page-heading" data-cy="logsPageHeading">Logs</h2>

    <p>There are {{ loggers.length }} loggers.</p>

    <span>Filter</span> <input type="text" [(ngModel)]="filter" class="form-control">

    <table class="table table-sm table-striped table-bordered" aria-describedby="logs-page-heading">
        <thead>
            <tr title="click to order">
                <th scope="col" (click)="orderProp = 'name'; reverse=!reverse"><span>Name</span></th>
                <th scope="col" (click)="orderProp = 'level'; reverse=!reverse"><span>Level</span></th>
            </tr>
        </thead>

        <tr *ngFor="let logger of (loggers | pureFilter:filter:'name' | orderBy:orderProp:reverse)">
            <td><small>{{ logger.name | slice:0:140 }}</small></td>
            <td>
                <button (click)="changeLevel(logger.name, 'TRACE')" [ngClass]="(logger.level=='TRACE') ? 'btn-primary' : 'btn-light'" class="btn btn-sm">TRACE</button>
                <button (click)="changeLevel(logger.name, 'DEBUG')" [ngClass]="(logger.level=='DEBUG') ? 'btn-success' : 'btn-light'" class="btn btn-sm">DEBUG</button>
                <button (click)="changeLevel(logger.name, 'INFO')" [ngClass]="(logger.level=='INFO') ? 'btn-info' : 'btn-light'" class="btn btn-sm">INFO</button>
                <button (click)="changeLevel(logger.name, 'WARN')" [ngClass]="(logger.level=='WARN') ? 'btn-warning' : 'btn-light'" class="btn btn-sm">WARN</button>
                <button (click)="changeLevel(logger.name, 'ERROR')" [ngClass]="(logger.level=='ERROR') ? 'btn-danger' : 'btn-light'" class="btn btn-sm">ERROR</button>
                <button (click)="changeLevel(logger.name, 'OFF')" [ngClass]="(logger.level=='OFF') ? 'btn-secondary' : 'btn-light'" class="btn btn-sm">OFF</button>
            </td>
        </tr>
    </table>
</div>
