// generators/client-2/templates/src/main/webapp/app/admin/user-management/_user-management.component.ts
import {Component, OnInit, Inject} from '@angular/core';
import { Response } from '@angular/http';

import { User } from './user.model';
import { UserService } from './user.service';
import { AlertService, ITEMS_PER_PAGE, ParseLinks, Principal } from '../../shared';
import { StateService } from "ui-router-ng2";

@Component({
    selector: 'user-mgmt',
    templateUrl: './user-management.html'
})
export class UserMgmtComponent implements OnInit {

    currentAccount: any;
    users: User[];
    error: any;
    success: any;
    <%_ if (databaseType !== 'cassandra') { _%>
    links: any;
    totalItems: any;
    queryCount: any;
    itemsPerPage: any;
    page: any;
    predicate: any;
    reverse: any;
    <%_ } _%>

    constructor(private userService: UserService,
                private parseLinks: ParseLinks,
                private alertService: AlertService,
                <%_ if (databaseType !== 'cassandra') { _%>
                private principal: Principal,
                <%_ } _%>
                private $state: StateService
    ) {
        this.itemsPerPage = ITEMS_PER_PAGE;
        this.page = 1;
        this.reverse = false;
        this.predicate = 'id';
    }

    ngOnInit() {
        this.loadAll();
        this.principal.identity().then((account) => {
            this.currentAccount = account;
        });
    }

    setActive (user, isActivated) {
        user.activated = isActivated;

        this.userService.update(user).subscribe(
            response => {
                if (response.status === 200) {
                    this.error = null;
                    this.success = 'OK';
                    this.loadAll();
                } else {
                    this.success = null;
                    this.error = 'ERROR';
                }
            });
    }
    loadAll () {
        this.userService.query({
            page: this.page -1,
            size: this.itemsPerPage,
            sort: this.sort()
        }).subscribe(
            (res: Response) => this.onSuccess(res.json(), res.headers),
            (res: Response) => this.onError(res.json())
        );
    }
    private onSuccess (data, headers) {
        //hide anonymous user from user management: it's a required user for Spring Security
        for (var i in data) {
            if (data[i]['login'] === 'anonymoususer') {
                data.splice(i, 1);
            }
        }
        <%_ if (databaseType !== 'cassandra') { _%>
        this.links = this.parseLinks.parse(headers.get('link'));
        this.totalItems = headers.get('X-Total-Count');
        this.queryCount = this.totalItems;
        // this.page = pagingParams.page;
        <%_ } _%>
        this.users = data;
    }
    private onError (error) {
        this.alertService.error(error.error, error.message, null);
    }
    <%_ if (databaseType !== 'cassandra') { _%>
    sort () {
        var result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
        if (this.predicate !== 'id') {
            result.push('id');
        }
        return result;
    }
    loadPage (page) {
        this.page = page;
        this.transition();
    }
    transition () {
        this.$state.transitionTo(this.$state.$current, {
            page: this.page,
            sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
        });
    }
    <%_ } _%>
}

<div>
    <h2 jhi-translate="userManagement.home.title">Users</h2>
    <jhi-alert></jhi-alert>
    <div class="row">
        <div class="col-md-4">
            <button class="btn btn-primary" uiSref="user-management.new">
                <span class="glyphicon glyphicon-flash"></span> <span jhi-translate="userManagement.home.createLabel">Create a new User</span>
            </button>
        </div>
    </div>
    <div class="table-responsive" *ngIf="users">
        <table class="table table-striped">
            <thead>
            <tr<% if (databaseType !== 'cassandra') { %> [attr.jh-sort]="predicate" [attr.ascending]="reverse" [attr.callback]="transition"<% } %>>
                <th<% if (databaseType !== 'cassandra') { %> [attr.jh-sort-by]="id"<% } %>><span jhi-translate="global.field.id">ID</span><%_ if (databaseType !== 'cassandra') { _%> <span class="glyphicon glyphicon-sort"></span><%_ } _%></th>
                <th<% if (databaseType !== 'cassandra') { %> [attr.jh-sort-by]="login"<% } %>><span jhi-translate="userManagement.login">Login</span><% if (databaseType !== 'cassandra') { %> <span class="glyphicon glyphicon-sort"></span><% } %></th>
                <th<% if (databaseType !== 'cassandra') { %> [attr.jh-sort-by]="email"<% } %>><span jhi-translate="userManagement.email">Email</span><% if (databaseType !== 'cassandra') { %> <span class="glyphicon glyphicon-sort"></span><% } %></th>
                <th></th>
                <%_ if (enableTranslation) { _%>
                <th <% if (databaseType !== 'cassandra') { %> [attr.jh-sort-by]="langKey"<% } %>> <span jhi-translate="userManagement.langKey">Lang Key</span><% if (databaseType !== 'cassandra') { %> <span class="glyphicon glyphicon-sort"></span><% } %></th>
                <%_ } _%>
                <th><span jhi-translate="userManagement.profiles">Profiles</span></th>
                <%_ if (databaseType !== 'cassandra') { _%>
                <th [attr.jh-sort-by]="createdDate"><span jhi-translate="userManagement.createdDate">Created Date</span> <span class="glyphicon glyphicon-sort"></span></th>
                <th [attr.jh-sort-by]="lastModifiedBy"><span jhi-translate="userManagement.lastModifiedBy">Last Modified By</span> <span class="glyphicon glyphicon-sort"></span></th>
                <th [attr.jh-sort-by]="lastModifiedDate"><span jhi-translate="userManagement.lastModifiedDate">Last Modified Date</span> <span class="glyphicon glyphicon-sort"></span></th>
                <%_ } _%>
                <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let user of users; trackBy: user?.id">
                <td><a uiSref="user-management-detail" [uiParams]="{ login: user.login }">{{user.id}}</a></td>
                <td>{{user.login}}</td>
                <td>{{user.email}}</td>
                <td>
                    <span class="label label-danger" (click)="setActive(user, true)" *ngIf="!user.activated"
                          jhi-translate="userManagement.deactivated" style="cursor: pointer;">Deactivated</span>
                    <span class="label label-success" (click)="setActive(user, false)" *ngIf="user.activated"
                          jhi-translate="userManagement.activated" style="cursor: pointer;">Activated</span>
                </td>
                <% if (enableTranslation) { %><td>{{user.langKey}}</td><% } %>
                <td>
                    <div *ngFor="let authority of user.authorities">
                        <span class="label label-info">{{ authority }}</span>
                    </div>
                </td><% if (databaseType == 'sql' || databaseType == 'mongodb') { %>
                <td>{{user.createdDate | date:'dd/MM/yy HH:mm'}}</td>
                <td>{{user.lastModifiedBy}}</td>
                <td>{{user.lastModifiedDate | date:'dd/MM/yy HH:mm'}}</td><% } %>
                <td class="text-right">
                    <div class="btn-group flex-btn-group-container">
                        <button type="submit"
                                uiSref="user-management-detail"
                                [uiParams]="{ login: user.login }"
                                class="btn btn-info btn-sm">
                            <span class="glyphicon glyphicon-eye-open"></span>
                            <span class="hidden-xs hidden-sm" jhi-translate="entity.action.view"></span>
                        </button>
                        <button type="submit"
                                uiSref="user-management.edit"
                                [uiParams]="{ login: user.login }"
                                class="btn btn-primary btn-sm">
                            <span class="glyphicon glyphicon-pencil"></span>
                            <span class="hidden-xs hidden-sm" jhi-translate="entity.action.edit"></span>
                        </button>
                        <button type="submit"
                                uiSref="user-management.delete"
                                [uiParams]="{ login: user.login }"
                                class="btn btn-danger btn-sm" [disabled]="currentAccount.login==user.login">
                            <span class="glyphicon glyphicon-remove-circle"></span>
                            <span class="hidden-xs hidden-sm" jhi-translate="entity.action.delete"></span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <%_ if (databaseType !== 'cassandra') { _%>
    <div class="text-center">
        <jhi-item-count [page]="page" [total]="queryCount" [items-per-page]="itemsPerPage"></jhi-item-count>
        <ngb-pagination size="sm" [collectionSize]="totalItems" [(page)]="page" (click)="loadPage(page)"></ngb-pagination>
    </div>
    <%_ } _%>
</div>

// generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management.js
import React, { Component } from 'react';
import { connect } from 'react-redux';

import Translate from 'react-translate-component';
import { getUsers } from '../../../reducers/administration';

export class UserManagement extends Component {

  constructor(props) {
    super(props);
    this.getUserList = this.getUserList.bind(this);
  }

  componentDidMount() {
    this.props.getUsers();
  }

  getUserList() {
    if (!this.props.isFetching) {
      this.props.getUsers();
    }
  }

  render() {
    const { userManagement, isFetching } = this.props;
    const users = (userManagement && userManagement.users) ? userManagement.users : [];
    return (
      <div className="well">
        <div>
          <h2 data-translate="gateway.title">Users</h2>
          FIX ME datatable pagination, activate/deactivate, action buttons
          <p>
            <button type="button" onClick={() => this.getUserList()} className={isFetching ? 'btn btn-danger' : 'btn btn-primary'} disabled={isFetching}>
              <span className="glyphicon glyphicon-refresh glyphicon-" />&nbsp;
              <Translate component="span" content="gateway.refresh.button" />
            </button>
          </p>
        </div>
        <div className="table-responsive">
          <table className="table table-striped">
            <thead>
              <tr jh-sort="vm.predicate" ascending="vm.reverse" callback="vm.transition()">
                <th jh-sort-by="id"><span translate="global.field.id">ID</span><span className="glyphicon glyphicon-sort" /></th>
                <th jh-sort-by="login"><span translate="userManagement.login">Login</span> <span className="glyphicon glyphicon-sort" /></th>
                <th jh-sort-by="email"><span translate="userManagement.email">Email</span> <span className="glyphicon glyphicon-sort" /></th>
                <th />
                <th jh-sort-by="langKey"> <span translate="userManagement.langKey">Lang Key</span> <span className="glyphicon glyphicon-sort" /></th>                                    <th><span translate="userManagement.profiles">Profiles</span></th>                                    <th jh-sort-by="createdDate"><span translate="userManagement.createdDate">Created Date</span> <span className="glyphicon glyphicon-sort" /></th>
                <th jh-sort-by="lastModifiedBy"><span translate="userManagement.lastModifiedBy">Last Modified By</span> <span className="glyphicon glyphicon-sort" /></th>
                <th jh-sort-by="lastModifiedDate"><span translate="userManagement.lastModifiedDate">Last Modified Date</span> <span className="glyphicon glyphicon-sort" /></th>
                <th />
              </tr>
            </thead>
            <tbody>
              {
              users.map((user, i) => (
                <tr key={`user-${i}`}>
                  <td><a>{user.id}</a></td>
                  <td>{user.login}</td>
                  <td>{user.email}</td>
                  <td>
                    {
                      user.activated ? (
                        <span
                          className="label label-success" ng-click="vm.setActive(user, false)" ng-show="user.activated"
                          translate="userManagement.activated" style={{ cursor: 'pointer' }}
                        >Activated</span>
                      ) : (
                        <span
                          className="label label-danger" ng-click="vm.setActive(user, true)" ng-show="!user.activated"
                          translate="userManagement.deactivated" style={{ cursor: 'pointer' }}
                        >Deactivated</span>
                      )
                    }
                  </td>
                  <td>{user.langKey}</td>
                  <td>
                    {
                      users.authorities ? (
                      users.authorities.map((authority, i) => (
                        <div>
                          <span className="label label-info">{authority}</span>
                        </div>
                      ))) : null
                    }
                  </td>
                  <td>{user.createdDate}</td>
                  <td>{user.lastModifiedBy}</td>
                  <td>{user.lastModifiedDate}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <button
                        type="submit"
                        className="btn btn-info btn-sm"
                      >
                        <span className="glyphicon glyphicon-eye-open" />
                        <span className="hidden-xs hidden-sm" ><Translate content="entity.action.view" /></span>
                      </button>
                      <button
                        type="submit"
                        className="btn btn-primary btn-sm"
                      >
                        <span className="glyphicon glyphicon-pencil" />
                        <span className="hidden-xs hidden-sm"><Translate content="entity.action.edit" /></span>
                      </button>
                      <button
                        type="submit"
                        className="btn btn-danger btn-sm" disabled={this.props.account.login === user.login}
                      >
                        <span className="glyphicon glyphicon-remove-circle" />
                        <span className="hidden-xs hidden-sm"><Translate content="entity.action.delete" /></span>
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            }
            </tbody>
          </table>
        </div>
      </div>
    );
  }
}

export default connect(
  (state => ({ userManagement: state.administration.userManagement, isFetching: state.administration.isFetching, account: state.authentication.account })),
  { getUsers }
)(UserManagement);
