// suneet/src/main/webapp/app/admin/user-management/detail/user-management-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { User } from '../user-management.model';

@Component({
  selector: 'my-prefix-user-mgmt-detail',
  templateUrl: './user-management-detail.component.html',
})
export class UserManagementDetailComponent implements OnInit {
  user: User | null = null;

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.route.data.subscribe(({ user }) => {
      this.user = user;
    });
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <div *ngIf="user">
      <h2>
        <span myPrefixTranslate="userManagement.detail.title">User</span> [<strong>{{ user.login }}</strong
        >]
      </h2>

      <dl class="row-md jh-entity-details">
        <dt><span myPrefixTranslate="userManagement.login">Login</span></dt>
        <dd>
          <span>{{ user.login }}</span>
          <span *ngIf="user.activated" class="badge bg-success" myPrefixTranslate="userManagement.activated">Activated</span>
          <span *ngIf="!user.activated" class="badge bg-danger" myPrefixTranslate="userManagement.deactivated">Deactivated</span>
        </dd>

        <dt><span myPrefixTranslate="userManagement.firstName">First name</span></dt>
        <dd>{{ user.firstName }}</dd>

        <dt><span myPrefixTranslate="userManagement.lastName">Last name</span></dt>
        <dd>{{ user.lastName }}</dd>

        <dt><span myPrefixTranslate="userManagement.email">Email</span></dt>
        <dd>{{ user.email }}</dd>

        <dt><span myPrefixTranslate="userManagement.langKey">Language</span></dt>
        <dd>{{ user.langKey }}</dd>

        <dt><span myPrefixTranslate="userManagement.createdBy">Created by</span></dt>
        <dd>{{ user.createdBy }}</dd>

        <dt><span myPrefixTranslate="userManagement.createdDate">Created date</span></dt>
        <dd>{{ user.createdDate | date: 'dd/MM/yy HH:mm' }}</dd>

        <dt><span myPrefixTranslate="userManagement.lastModifiedBy">Modified by</span></dt>
        <dd>{{ user.lastModifiedBy }}</dd>

        <dt><span myPrefixTranslate="userManagement.lastModifiedDate">Modified date</span></dt>
        <dd>{{ user.lastModifiedDate | date: 'dd/MM/yy HH:mm' }}</dd>

        <dt><span myPrefixTranslate="userManagement.profiles">Profiles</span></dt>
        <dd>
          <ul class="list-unstyled">
            <li *ngFor="let authority of user.authorities">
              <span class="badge bg-info">{{ authority }}</span>
            </li>
          </ul>
        </dd>
      </dl>

      <button type="submit" routerLink="../../" class="btn btn-info">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span myPrefixTranslate="entity.action.back">Back</span>
      </button>
    </div>
  </div>
</div>

// generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom';
import { Button } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FaArrowLeft } from 'react-icons/lib/fa';

import { ICrudGetAction } from '../../../shared/model/redux-action.type';
import { getUser } from '../../../reducers/user-management';

export interface IUserManagementDetailProps {
  getUser: ICrudGetAction;
  user: any;
  match: any;
}
export class UserManagementDetail extends React.Component<IUserManagementDetailProps, undefined> {

  componentDidMount() {
    this.props.getUser(this.props.match.params.login);
  }

  render() {
    const { user } = this.props;
    return (
      <div>
        <h2>
          <Translate contentKey="userManagement.detail.title">User</Translate> [<b>{user.login}</b>]
        </h2>
        <dl className="row-md jh-entity-details">
          <dt><Translate contentKey="userManagement.login">Login</Translate></dt>
          <dd>
            <span>{user.login}</span>&nbsp;
            {
              user.activated ? (
                <span className="badge badge-success"><Translate contentKey="userManagement.activated">Activated</Translate></span>
              ) : (
                <span className="badge badge-danger"><Translate contentKey="userManagement.deactivated">Deactivated</Translate></span>
              )
            }
          </dd>
          <dt><Translate contentKey="userManagement.firstName">First Name</Translate></dt>
          <dd>{user.firstName}</dd>
          <dt><Translate contentKey="userManagement.lastName">Last Name</Translate></dt>
          <dd>{user.lastName}</dd>
          <dt><Translate contentKey="userManagement.email">Email</Translate></dt>
          <dd>{user.email}</dd>
          <%_ if (enableTranslation) { _%>
          <dt><Translate contentKey="userManagement.langKey">Lang Key</Translate></dt>
          <dd>{user.langKey}</dd>
          <%_ } _%>
          <dt><Translate contentKey="userManagement.createdBy">Created By</Translate></dt>
          <dd>{user.createdBy}</dd>
          <dt><Translate contentKey="userManagement.createdDate">Created Date</Translate></dt>
          <dd>{user.createdDate}</dd>
          <dt><Translate contentKey="userManagement.lastModifiedBy">Last Modified By</Translate></dt>
          <dd>{user.lastModifiedBy}</dd>
          <dt><Translate contentKey="userManagement.lastModifiedDate">Last Modified Date</Translate></dt>
          <dd>{user.lastModifiedDate}</dd>
          <dt><Translate contentKey="userManagement.profiles">Profiles</Translate></dt>
          <dd>
            <ul className="list-unstyled">
              {
                user.authorities ? (
                user.authorities.map((authority, i) => (
                  <li key={`user-auth-${i}`}>
                    <span className="badge badge-info">{authority}</span>
                  </li>
                ))) : null
              }
            </ul>
          </dd>
        </dl>
        <Button
          tag={Link} to="/admin/user-management" replace
          color="info"
        >
          <FaArrowLeft/> <span className="d-none d-md-inline" ><Translate contentKey="entity.action.back">Back</Translate></span>
        </Button>
      </div>
    );
  }
}

const mapStateToProps = storeState => ({
  user: storeState.userManagement.user
});

const mapDispatchToProps = { getUser };

export default connect(mapStateToProps, mapDispatchToProps)(UserManagementDetail);
