// sandbox/admin/src/main/webapp/app/modules/administration/user-management/user-management-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Label, Row, Col } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField, AvFeedback } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { locales, languages } from 'app/config/translation';
import { getUser, getRoles, updateUser, createUser, reset } from './user-management.reducer';
import { IRootState } from 'app/shared/reducers';

export interface IUserManagementUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ login: string }> {}

export const UserManagementUpdate = (props: IUserManagementUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.login);

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getUser(props.match.params.login);
    }
    props.getRoles();
    return () => {
      props.reset();
    };
  }, []);

  const handleClose = () => {
    props.history.push('/admin/user-management');
  };

  const saveUser = (event, values) => {
    if (isNew) {
      props.createUser(values);
    } else {
      props.updateUser(values);
    }
    handleClose();
  };

  const isInvalid = false;
  const { user, loading, updating, roles } = props;

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h1>
            <Translate contentKey="userManagement.home.createOrEditLabel">Create or edit a User</Translate>
          </h1>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm onValidSubmit={saveUser}>
              {user.id ? (
                <AvGroup>
                  <Label for="id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvField type="text" className="form-control" name="id" required readOnly value={user.id} />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label for="login">
                  <Translate contentKey="userManagement.login">Login</Translate>
                </Label>
                <AvField
                  type="text"
                  className="form-control"
                  name="login"
                  validate={{
                    required: {
                      value: true,
                      errorMessage: translate('register.messages.validate.login.required'),
                    },
                    pattern: {
                      value: '^[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$|^[_.@A-Za-z0-9-]+$',
                      errorMessage: translate('register.messages.validate.login.pattern'),
                    },
                    minLength: {
                      value: 1,
                      errorMessage: translate('register.messages.validate.login.minlength'),
                    },
                    maxLength: {
                      value: 50,
                      errorMessage: translate('register.messages.validate.login.maxlength'),
                    },
                  }}
                  value={user.login}
                />
              </AvGroup>
              <AvGroup>
                <Label for="firstName">
                  <Translate contentKey="userManagement.firstName">First Name</Translate>
                </Label>
                <AvField
                  type="text"
                  className="form-control"
                  name="firstName"
                  validate={{
                    maxLength: {
                      value: 50,
                      errorMessage: translate('entity.validation.maxlength', { max: 50 }),
                    },
                  }}
                  value={user.firstName}
                />
              </AvGroup>
              <AvGroup>
                <Label for="lastName">
                  <Translate contentKey="userManagement.lastName">Last Name</Translate>
                </Label>
                <AvField
                  type="text"
                  className="form-control"
                  name="lastName"
                  validate={{
                    maxLength: {
                      value: 50,
                      errorMessage: translate('entity.validation.maxlength', { max: 50 }),
                    },
                  }}
                  value={user.lastName}
                />
                <AvFeedback>This field cannot be longer than 50 characters.</AvFeedback>
              </AvGroup>
              <AvGroup>
                <AvField
                  name="email"
                  label={translate('global.form.email.label')}
                  placeholder={translate('global.form.email.placeholder')}
                  type="email"
                  validate={{
                    required: {
                      value: true,
                      errorMessage: translate('global.messages.validate.email.required'),
                    },
                    email: {
                      errorMessage: translate('global.messages.validate.email.invalid'),
                    },
                    minLength: {
                      value: 5,
                      errorMessage: translate('global.messages.validate.email.minlength'),
                    },
                    maxLength: {
                      value: 254,
                      errorMessage: translate('global.messages.validate.email.maxlength'),
                    },
                  }}
                  value={user.email}
                />
              </AvGroup>
              <AvGroup check>
                <Label>
                  <AvInput type="checkbox" name="activated" value={user.activated} checked={user.activated} disabled={!user.id} />{' '}
                  <Translate contentKey="userManagement.activated">Activated</Translate>
                </Label>
              </AvGroup>
              <AvGroup>
                <Label for="langKey">
                  <Translate contentKey="userManagement.langKey">Language Key</Translate>
                </Label>
                <AvField type="select" className="form-control" name="langKey" value={user.langKey || locales[0]}>
                  {locales.map(locale => (
                    <option value={locale} key={locale}>
                      {languages[locale].name}
                    </option>
                  ))}
                </AvField>
              </AvGroup>
              <AvGroup>
                <Label for="authorities">
                  <Translate contentKey="userManagement.profiles">Profiles</Translate>
                </Label>
                <AvInput type="select" className="form-control" name="authorities" value={user.authorities} multiple>
                  {roles.map(role => (
                    <option value={role} key={role}>
                      {role}
                    </option>
                  ))}
                </AvInput>
              </AvGroup>
              <Button tag={Link} to="/admin/user-management" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" type="submit" disabled={isInvalid || updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  user: storeState.userManagement.user,
  roles: storeState.userManagement.authorities,
  loading: storeState.userManagement.loading,
  updating: storeState.userManagement.updating,
});

const mapDispatchToProps = { getUser, getRoles, updateUser, createUser, reset };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(UserManagementUpdate);

// gateway/src/main/webapp/app/admin/user-management/update/user-management-update.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormControl, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { LANGUAGES } from 'app/config/language.constants';
import { IUser } from '../user-management.model';
import { UserManagementService } from '../service/user-management.service';

const userTemplate = {} as IUser;

const newUser: IUser = {
  langKey: 'en',
  activated: true,
} as IUser;

@Component({
  selector: 'jhi-user-mgmt-update',
  templateUrl: './user-management-update.component.html',
  imports: [SharedModule, FormsModule, ReactiveFormsModule],
})
export default class UserManagementUpdateComponent implements OnInit {
  languages = LANGUAGES;
  authorities = signal<string[]>([]);
  isSaving = signal(false);

  editForm = new FormGroup({
    id: new FormControl(userTemplate.id),
    login: new FormControl(userTemplate.login, {
      nonNullable: true,
      validators: [
        Validators.required,
        Validators.minLength(1),
        Validators.maxLength(50),
        Validators.pattern('^[a-zA-Z0-9!$&*+=?^_`{|}~.-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$|^[_.@A-Za-z0-9-]+$'),
      ],
    }),
    firstName: new FormControl(userTemplate.firstName, { validators: [Validators.maxLength(50)] }),
    lastName: new FormControl(userTemplate.lastName, { validators: [Validators.maxLength(50)] }),
    email: new FormControl(userTemplate.email, {
      nonNullable: true,
      validators: [Validators.minLength(5), Validators.maxLength(254), Validators.email],
    }),
    activated: new FormControl(userTemplate.activated, { nonNullable: true }),
    langKey: new FormControl(userTemplate.langKey, { nonNullable: true }),
    authorities: new FormControl(userTemplate.authorities, { nonNullable: true }),
  });

  private readonly userService = inject(UserManagementService);
  private readonly route = inject(ActivatedRoute);

  ngOnInit(): void {
    this.route.data.subscribe(({ user }) => {
      if (user) {
        this.editForm.reset(user);
      } else {
        this.editForm.reset(newUser);
      }
    });
    this.userService.authorities().subscribe(authorities => this.authorities.set(authorities));
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving.set(true);
    const user = this.editForm.getRawValue();
    if (user.id !== null) {
      this.userService.update(user).subscribe({
        next: () => this.onSaveSuccess(),
        error: () => this.onSaveError(),
      });
    } else {
      this.userService.create(user).subscribe({
        next: () => this.onSaveSuccess(),
        error: () => this.onSaveError(),
      });
    }
  }

  private onSaveSuccess(): void {
    this.isSaving.set(false);
    this.previousState();
  }

  private onSaveError(): void {
    this.isSaving.set(false);
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    <form name="editForm" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="myUserLabel" jhiTranslate="userManagement.home.createOrEditLabel">Create or edit a user</h2>

      <jhi-alert-error />

      <div class="mb-3" [hidden]="!editForm.value.id">
        <label class="form-label" for="field_id" jhiTranslate="global.field.id">ID</label>
        <input type="text" id="field_id" class="form-control" name="id" formControlName="id" readonly />
      </div>

      <div class="mb-3">
        <label class="form-label" for="field_login" jhiTranslate="userManagement.login">Login</label>
        <input type="text" id="field_login" class="form-control" name="login" formControlName="login" />

        @let loginRef = editForm.get('login')!;
        @if (loginRef.invalid && (loginRef.dirty || loginRef.touched)) {
          <div>
            @if (loginRef?.errors?.required) {
              <small class="form-text text-danger" jhiTranslate="entity.validation.required">This field is required.</small>
            }

            @if (loginRef?.errors?.maxlength) {
              <small class="form-text text-danger" jhiTranslate="entity.validation.maxlength" [translateValues]="{ max: '50' }"
                >This field cannot be longer than 50 characters.</small
              >
            }

            @if (loginRef?.errors?.pattern) {
              <small class="form-text text-danger" jhiTranslate="entity.validation.patternLogin"
                >This field can only contain letters, digits and e-mail addresses.</small
              >
            }
          </div>
        }
      </div>

      <div class="mb-3">
        <label class="form-label" for="field_firstName" jhiTranslate="userManagement.firstName">First name</label>
        <input type="text" id="field_firstName" class="form-control" name="firstName" formControlName="firstName" />

        @let firstNameRef = editForm.get('firstName')!;
        @if (firstNameRef.invalid && (firstNameRef.dirty || firstNameRef.touched)) {
          <div>
            @if (firstNameRef?.errors?.maxlength) {
              <small class="form-text text-danger" jhiTranslate="entity.validation.maxlength" [translateValues]="{ max: '50' }"
                >This field cannot be longer than 50 characters.</small
              >
            }
          </div>
        }
      </div>

      <div class="mb-3">
        <label class="form-label" for="field_lastName" jhiTranslate="userManagement.lastName">Last name</label>
        <input type="text" id="field_lastName" class="form-control" name="lastName" formControlName="lastName" />

        @let lastNameRef = editForm.get('lastName')!;
        @if (lastNameRef.invalid && (lastNameRef.dirty || lastNameRef.touched)) {
          <div>
            @if (lastNameRef?.errors?.maxlength) {
              <small class="form-text text-danger" jhiTranslate="entity.validation.maxlength" [translateValues]="{ max: '50' }"
                >This field cannot be longer than 50 characters.</small
              >
            }
          </div>
        }
      </div>

      <div class="mb-3">
        <label class="form-label" for="field_email" jhiTranslate="userManagement.email">Email</label>
        <input type="email" id="field_email" class="form-control" name="email" formControlName="email" />

        @let emailRef = editForm.get('email')!;
        @if (emailRef.invalid && (emailRef.dirty || emailRef.touched)) {
          <div>
            @if (emailRef?.errors?.required) {
              <small class="form-text text-danger" jhiTranslate="entity.validation.required">This field is required.</small>
            }

            @if (emailRef?.errors?.maxlength) {
              <small class="form-text text-danger" jhiTranslate="entity.validation.maxlength" [translateValues]="{ max: '100' }"
                >This field cannot be longer than 100 characters.</small
              >
            }

            @if (emailRef?.errors?.minlength) {
              <small class="form-text text-danger" jhiTranslate="entity.validation.minlength" [translateValues]="{ min: '5' }"
                >This field is required to be at least 5 characters.</small
              >
            }

            @if (emailRef?.errors?.email) {
              <small class="form-text text-danger" jhiTranslate="global.messages.validate.email.invalid">Your email is invalid.</small>
            }
          </div>
        }
      </div>

      <div class="form-check">
        <label class="form-check-label" for="activated">
          <input
            class="form-check-input"
            [attr.disabled]="editForm.value.id === undefined ? 'disabled' : null"
            type="checkbox"
            id="activated"
            name="activated"
            formControlName="activated"
          />
          <span jhiTranslate="userManagement.activated">Activated</span>
        </label>
      </div>

      @if (languages && languages.length > 0) {
        <div class="mb-3">
          <label class="form-label" for="langKey" jhiTranslate="userManagement.langKey">Language</label>
          <select class="form-control" id="langKey" name="langKey" formControlName="langKey">
            @for (language of languages; track $index) {
              <option [value]="language">{{ language | findLanguageFromKey }}</option>
            }
          </select>
        </div>
      }

      <div class="mb-3">
        <label class="form-label" for="field_authority" jhiTranslate="userManagement.profiles">Profiles</label>
        <select class="form-control" id="field_authority" multiple name="authority" formControlName="authorities">
          @for (authority of authorities(); track $index) {
            <option [value]="authority">{{ authority }}</option>
          }
        </select>
      </div>
      <button type="button" class="btn btn-secondary" (click)="previousState()">
        <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
      </button>

      <button type="submit" [disabled]="editForm.invalid || isSaving()" class="btn btn-primary">
        <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
      </button>
    </form>
  </div>
</div>
