// sandraapp/src/main/webapp/app/admin/metrics/metrics.component.ts
import { Component, OnInit, ChangeDetectionStrategy, ChangeDetectorRef } from '@angular/core';
import { flatMap } from 'rxjs/operators';

import { MetricsService, Metrics, MetricsKey, ThreadDump, Thread } from './metrics.service';

@Component({
  selector: 'jhi-metrics',
  templateUrl: './metrics.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MetricsComponent implements OnInit {
  metrics?: Metrics;
  threads?: Thread[];
  updatingMetrics = true;

  constructor(private metricsService: MetricsService, private changeDetector: ChangeDetectorRef) {}

  ngOnInit(): void {
    this.refresh();
  }

  refresh(): void {
    this.updatingMetrics = true;
    this.metricsService
      .getMetrics()
      .pipe(
        flatMap(
          () => this.metricsService.threadDump(),
          (metrics: Metrics, threadDump: ThreadDump) => {
            this.metrics = metrics;
            this.threads = threadDump.threads;
            this.updatingMetrics = false;
            this.changeDetector.detectChanges();
          }
        )
      )
      .subscribe();
  }

  metricsKeyExists(key: MetricsKey): boolean {
    return this.metrics && this.metrics[key];
  }

  metricsKeyExistsAndObjectNotEmpty(key: MetricsKey): boolean {
    return this.metrics && this.metrics[key] && JSON.stringify(this.metrics[key]) !== '{}';
  }
}

<div>
    <h2>
        <span id="metrics-page-heading" data-cy="metricsPageHeading">Application Metrics</span>

        <button class="btn btn-primary float-right" (click)="refresh()">
            <fa-icon icon="sync"></fa-icon> <span>Refresh</span>
        </button>
    </h2>

    <h3>JVM Metrics</h3>

    <div class="row" *ngIf="metrics && !updatingMetrics">
        <jhi-jvm-memory
            class="col-md-4"
            [updating]="updatingMetrics"
            [jvmMemoryMetrics]="metrics.jvm">
        </jhi-jvm-memory>

        <jhi-jvm-threads
            class="col-md-4"
            [threadData]="threads">
        </jhi-jvm-threads>

        <jhi-metrics-system
            class="col-md-4"
            [updating]="updatingMetrics"
            [systemMetrics]="metrics.processMetrics">
        </jhi-metrics-system>
    </div>

    <div *ngIf="metrics && metricsKeyExists('garbageCollector')">
        <h3>Garbage collector statistics</h3>

        <jhi-metrics-garbagecollector
            [updating]="updatingMetrics"
            [garbageCollectorMetrics]="metrics.garbageCollector">
        </jhi-metrics-garbagecollector>
    </div>

    <div class="well well-lg" *ngIf="updatingMetrics">Updating...</div>

    <jhi-metrics-request
        *ngIf="metrics && metricsKeyExists('http.server.requests')"
        [updating]="updatingMetrics"
        [requestMetrics]="metrics['http.server.requests']">
    </jhi-metrics-request>

    <jhi-metrics-endpoints-requests
        *ngIf="metrics && metricsKeyExists('services')"
        [updating]="updatingMetrics"
        [endpointsRequestsMetrics]="metrics.services">
    </jhi-metrics-endpoints-requests>

    <jhi-metrics-cache
        *ngIf="metrics && metricsKeyExists('cache')"
        [updating]="updatingMetrics"
        [cacheMetrics]="metrics.cache">
    </jhi-metrics-cache>

    <jhi-metrics-datasource
        *ngIf="metrics && metricsKeyExistsAndObjectNotEmpty('databases')"
        [updating]="updatingMetrics"
        [datasourceMetrics]="metrics.databases">
    </jhi-metrics-datasource>
</div>

// sandbox/admin/src/main/webapp/app/modules/administration/metrics/metrics.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Button, Col, Row } from 'reactstrap';
import {
  CacheMetrics,
  DatasourceMetrics,
  GarbageCollectorMetrics,
  HttpRequestMetrics,
  JvmMemory,
  JvmThreads,
  EndpointsRequestsMetrics,
  SystemMetrics,
  Translate,
} from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_TIMESTAMP_FORMAT, APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT, APP_WHOLE_NUMBER_FORMAT } from 'app/config/constants';
import { systemMetrics, systemThreadDump } from '../administration.reducer';
import { IRootState } from 'app/shared/reducers';

export interface IMetricsPageProps extends StateProps, DispatchProps {}

export const MetricsPage = (props: IMetricsPageProps) => {
  useEffect(() => {
    props.systemMetrics();
    props.systemThreadDump();
  }, []);

  const getMetrics = () => {
    if (!props.isFetching) {
      props.systemMetrics();
      props.systemThreadDump();
    }
  };

  const { metrics, threadDump, isFetching } = props;

  return (
    <div>
      <h2 id="metrics-page-heading" data-cy="metricsPageHeading">
        Application Metrics
      </h2>
      <p>
        <Button onClick={getMetrics} color={isFetching ? 'btn btn-danger' : 'btn btn-primary'} disabled={isFetching}>
          <FontAwesomeIcon icon="sync" />
          &nbsp;
          <Translate component="span" contentKey="health.refresh.button">
            Refresh
          </Translate>
        </Button>
      </p>
      <hr />

      <Row>
        <Col sm="12">
          <h3>JVM Metrics</h3>
          <Row>
            <Col md="4">
              {metrics && metrics.jvm ? <JvmMemory jvmMetrics={metrics.jvm} wholeNumberFormat={APP_WHOLE_NUMBER_FORMAT} /> : ''}
            </Col>
            <Col md="4">{threadDump ? <JvmThreads jvmThreads={threadDump} wholeNumberFormat={APP_WHOLE_NUMBER_FORMAT} /> : ''}</Col>
            <Col md="4">
              {metrics && metrics.processMetrics ? (
                <SystemMetrics
                  systemMetrics={metrics.processMetrics}
                  wholeNumberFormat={APP_WHOLE_NUMBER_FORMAT}
                  timestampFormat={APP_TIMESTAMP_FORMAT}
                />
              ) : (
                ''
              )}
            </Col>
          </Row>
        </Col>
      </Row>

      {metrics && metrics.garbageCollector ? (
        <GarbageCollectorMetrics garbageCollectorMetrics={metrics.garbageCollector} wholeNumberFormat={APP_WHOLE_NUMBER_FORMAT} />
      ) : (
        ''
      )}
      {metrics && metrics['http.server.requests'] ? (
        <HttpRequestMetrics
          requestMetrics={metrics['http.server.requests']}
          twoDigitAfterPointFormat={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT}
          wholeNumberFormat={APP_WHOLE_NUMBER_FORMAT}
        />
      ) : (
        ''
      )}
      {metrics && metrics.services ? (
        <EndpointsRequestsMetrics endpointsRequestsMetrics={metrics.services} wholeNumberFormat={APP_WHOLE_NUMBER_FORMAT} />
      ) : (
        ''
      )}

      {metrics.cache ? (
        <Row>
          <Col sm="12">
            <CacheMetrics cacheMetrics={metrics.cache} twoDigitAfterPointFormat={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT} />
          </Col>
        </Row>
      ) : (
        ''
      )}

      {metrics.databases && JSON.stringify(metrics.databases) !== '{}' ? (
        <Row>
          <Col sm="12">
            <DatasourceMetrics datasourceMetrics={metrics.databases} twoDigitAfterPointFormat={APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT} />
          </Col>
        </Row>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  metrics: storeState.administration.metrics,
  isFetching: storeState.administration.loading,
  threadDump: storeState.administration.threadDump,
});

const mapDispatchToProps = { systemMetrics, systemThreadDump };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(MetricsPage);
