// sandbox/admin/src/main/webapp/app/modules/account/password-reset/init/password-reset-init.tsx
import React from 'react';
import { Translate, translate } from 'react-jhipster';
import { connect } from 'react-redux';
import { AvForm, AvField } from 'availity-reactstrap-validation';
import { Button, Alert, Col, Row } from 'reactstrap';

import { handlePasswordResetInit, reset } from '../password-reset.reducer';

export type IPasswordResetInitProps = DispatchProps;

export class PasswordResetInit extends React.Component<IPasswordResetInitProps> {
  componentWillUnmount() {
    this.props.reset();
  }

  handleValidSubmit = (event, values) => {
    this.props.handlePasswordResetInit(values.email);
    event.preventDefault();
  };

  render() {
    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h1>
              <Translate contentKey="reset.request.title">Reset your password</Translate>
            </h1>
            <Alert color="warning">
              <p>
                <Translate contentKey="reset.request.messages.info">Enter the email address you used to register</Translate>
              </p>
            </Alert>
            <AvForm onValidSubmit={this.handleValidSubmit}>
              <AvField
                name="email"
                label={translate('global.form.email.label')}
                placeholder={translate('global.form.email.placeholder')}
                type="email"
                validate={{
                  required: { value: true, errorMessage: translate('global.messages.validate.email.required') },
                  minLength: { value: 5, errorMessage: translate('global.messages.validate.email.minlength') },
                  maxLength: { value: 254, errorMessage: translate('global.messages.validate.email.maxlength') },
                }}
                data-cy="emailResetPassword"
              />
              <Button color="primary" type="submit" data-cy="submit">
                <Translate contentKey="reset.request.form.button">Reset password</Translate>
              </Button>
            </AvForm>
          </Col>
        </Row>
      </div>
    );
  }
}

const mapDispatchToProps = { handlePasswordResetInit, reset };

type DispatchProps = typeof mapDispatchToProps;

export default connect(null, mapDispatchToProps)(PasswordResetInit);

// generators/client-2/templates/src/main/webapp/app/account/password-reset/init/_password-reset-init.component.ts
import { Component, OnInit, Inject, Renderer, ElementRef } from '@angular/core';
import { PasswordResetInit } from './password-reset-init.service';

@Component({
    selector: 'password-reset-init',
    templateUrl: './password-reset-init.component.html'
})
export class PasswordResetInitComponent implements OnInit {
    error: string;
    errorEmailNotExists: string;
    resetAccount: any;
    success: string;

    constructor(private passwordResetInit: PasswordResetInit, private elementRef: ElementRef, private renderer: Renderer) {}

    ngOnInit() {
        this.resetAccount = {};
    }

    ngAfterViewInit() {
        this.renderer.invokeElementMethod(this.elementRef.nativeElement.querySelector('#email'), 'focus', []);
    }

    requestReset () {

        this.error = null;
        this.errorEmailNotExists = null;

        this.passwordResetInit.save(this.resetAccount.email).subscribe(() => {
            this.success = 'OK';
        }, (response) => {
            this.success = null;
            if (response.status === 400 && response.data === 'e-mail address not registered') {
                this.errorEmailNotExists = 'ERROR';
            } else {
                this.error = 'ERROR';
            }
        });
    }
}

<div>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1 jhi-translate="reset.request.title">Reset your password</h1>

            <div class="alert alert-danger" jhi-translate="reset.request.messages.notfound" *ngIf="errorEmailNotExists">
                <strong>E-Mail address isn't registered!</strong> Please check and try again.
            </div>

            <div class="alert alert-warning" *ngIf="!success">
                <p jhi-translate="reset.request.messages.info">Enter the e-mail address you used to register.</p>
            </div>

            <div class="alert alert-success" *ngIf="success == 'OK'">
                <p jhi-translate="reset.request.messages.success">Check your e-mails for details on how to reset your password.</p>
            </div>

            <form *ngIf="!success" name="form" role="form" (ngSubmit)="requestReset()" #resetRequestForm="ngForm">
                <div class="form-group">
                    <label class="control-label" for="email" jhi-translate="global.form.email">E-mail</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="{{'global.form.email.placeholder' | translate}}"
                           [(ngModel)]="resetAccount.email" minlength=5 maxlength=100 #emailInput="ngModel" required>
                    <div *ngIf="emailInput.dirty && emailInput.invalid">
                        <p class="help-block"
                           *ngIf="emailInput.errors.required" jhi-translate="global.messages.validate.email.required">
                            Your e-mail is required.
                        </p>
                        <p class="help-block"
                           *ngIf="emailInput.errors.email" jhi-translate="global.messages.validate.email.invalid">
                            Your e-mail is invalid.
                        </p>
                        <p class="help-block"
                           *ngIf="emailInput.errors.minlength" jhi-translate="global.messages.validate.email.minlength">
                            Your e-mail is required to be at least 5 characters.
                        </p>
                        <p class="help-block"
                           *ngIf="emailInput.errors.maxlength" jhi-translate="global.messages.validate.email.maxlength">
                            Your e-mail cannot be longer than 100 characters.
                        </p>
                    </div>
                </div>
                <button type="submit" [disabled]="resetRequestForm.form.invalid" class="btn btn-primary" jhi-translate="reset.request.form.button">Reset</button>
            </form>

        </div>
    </div>
</div>
