// generators/client/templates/react/src/main/webapp/app/modules/administration/user-management/user-management-dialog.tsx
import * as React from 'react';
import { connect } from 'react-redux';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvFeedback } from 'availity-reactstrap-validation';
import { Translate, ICrudGetAction, ICrudPutAction } from 'react-jhipster';
import { FaBan, FaFloppyO } from 'react-icons/lib/fa';

import { getUser, getRoles, updateUser, createUser } from '../../../reducers/user-management';
<%_ if (enableTranslation) { _%>
import { locales } from '../../../config/translation';
<%_ } _%>

export interface IUserManagementDialogProps {
  getUser: ICrudGetAction;
  getRoles: ICrudGetAction;
  updateUser: ICrudPutAction;
  createUser: ICrudPutAction;
  loading: boolean;
  updating: boolean;
  user: any;
  roles: any[];
  match: any;
  history: any;
}

export interface IUserManagementDialogState {
  showModal: boolean;
  isNew: boolean;
}

export class UserManagementDialog extends React.Component<IUserManagementDialogProps, IUserManagementDialogState> {

  constructor(props) {
    super(props);
    this.state = {
      showModal: true,
      isNew: !this.props.match.params || !this.props.match.params.login
    };
  }

  componentDidMount() {
    !this.state.isNew && this.props.getUser(this.props.match.params.login);
    this.props.getRoles();
  }

  saveUSer = (event, errors, values) => {
    if (this.state.isNew) {
      this.props.createUser(values);
    } else {
      this.props.updateUser(values);
    }
    this.handleClose();
  }

  handleClose = () => {
    this.setState({
        showModal: false
    });
    this.props.history.push('/admin/user-management');
  }

  render() {
    const isInvalid = false;
    const { user, loading, updating, roles } = this.props;
    const { showModal, isNew } = this.state;
    return (
      <Modal
        isOpen={showModal} modalTransition={{ timeout: 20 }} backdropTransition={{ timeout: 10 }}
        toggle={this.handleClose} size="lg"
      >
      <ModalHeader toggle={this.handleClose}><Translate contentKey="userManagement.home.createOrEditLabel">Create or edit a User</Translate></ModalHeader>
      { loading ? <p>Loading...</p>
      : <AvForm model={isNew ? {} : user} onSubmit={this.saveUSer} >
          <ModalBody>
            { user.id ?
              <AvGroup>
                <Label for="id"><Translate contentKey="global.field.id">ID</Translate></Label>
                <AvInput type="text" className="form-control" name="id" required readOnly/>
              </AvGroup>
              : null
            }
            <AvGroup>
              <Label for="login"><Translate contentKey="userManagement.login">Login</Translate></Label>
              <AvInput type="text" className="form-control" name="login" required />
              <AvFeedback>This field is required.</AvFeedback>
              <AvFeedback>This field cannot be longer than 50 characters.</AvFeedback>
            </AvGroup>
            <AvGroup>
              <Label for="firstName"><Translate contentKey="userManagement.firstName">First Name</Translate></Label>
              <AvInput type="text" className="form-control" name="firstName" />
              <AvFeedback>This field cannot be longer than 50 characters.</AvFeedback>
            </AvGroup>
            <AvGroup>
              <Label for="lastName"><Translate contentKey="userManagement.lastName">Last Name</Translate></Label>
              <AvInput type="text" className="form-control" name="lastName" />
              <AvFeedback>This field cannot be longer than 50 characters.</AvFeedback>
            </AvGroup>
            <AvGroup>
              <Label for="email"><Translate contentKey="userManagement.email">E-mail</Translate></Label>
              <AvInput type="email" className="form-control" name="email" required/>
              <AvFeedback>This field is required.</AvFeedback>
              <AvFeedback>This field cannot be longer than 254 characters.</AvFeedback>
              <AvFeedback>This field is required to be at least 5 characters.</AvFeedback>
            </AvGroup>
            <AvGroup>
              <Label check>
                <AvInput type="checkbox" name="activated" /> <Translate contentKey="userManagement.activated">Activated</Translate>
              </Label>
              <AvFeedback>This field is required.</AvFeedback>
              <AvFeedback>This field cannot be longer than 254 characters.</AvFeedback>
              <AvFeedback>This field is required to be at least 5 characters.</AvFeedback>
            </AvGroup>
            <%_ if (enableTranslation) { _%>
            <AvGroup>
              <Label for="langKey"><Translate contentKey="userManagement.langKey">Language Key</Translate></Label>
              <AvInput type="select" className="form-control" name="langKey">
                {locales.map(lang => <option value={lang} key={lang}>{lang}</option>)}
              </AvInput>
            </AvGroup>
            <%_ } _%>
            <AvGroup>
              <Label for="authorities"><Translate contentKey="userManagement.profiles">Language Key</Translate></Label>
              <AvInput type="select" className="form-control" name="authorities" multiple>
                {roles.map(role => <option value={role} key={role}>{role}</option>)}
              </AvInput>
            </AvGroup>
          </ModalBody>
          <ModalFooter>
            <Button color="secondary" onClick={this.handleClose}>
              <FaBan/>&nbsp;
              <Translate contentKey="entity.action.cancel">Cancel</Translate>
            </Button>
            <Button color="primary" type="submit" disabled={isInvalid || updating}>
              <FaFloppyO/>&nbsp;
              <Translate contentKey="entity.action.save">Save</Translate>
            </Button>
          </ModalFooter>
        </AvForm>
      }
    </Modal>
    );
  }
}

const mapStateToProps = storeState => ({
  user: storeState.userManagement.user,
  roles: storeState.userManagement.authorities,
  loading: storeState.userManagement.loading,
  updating: storeState.userManagement.updating
});

const mapDispatchToProps = { getUser, getRoles, updateUser, createUser };

export default connect(mapStateToProps, mapDispatchToProps)(UserManagementDialog);

// generators/client-2/templates/src/main/webapp/app/admin/user-management/_user-management-dialog.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { User } from './user.model';
import { UserService } from './user.service';
<%_ if (enableTranslation){ _%>
import { <%=jhiPrefixCapitalized%>LanguageService } from '../../shared';
<%_ }_%>

@Component({
    selector: 'user-mgmt-dialog',
    templateUrl: 'app/admin/user-management/user-management-dialog.component.html'
})
export class UserMgmtDialogComponent implements OnInit {

    user: User;
    languages: any[];
    authorities: any[];
    isSaving: Boolean;

    constructor(
        public activeModal: NgbActiveModal,
        <%_ if (enableTranslation){ _%>
        private languageService: <%=jhiPrefixCapitalized%>LanguageService,
        <%_ } _%>
        private userService: UserService
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.authorities = ['ROLE_USER', 'ROLE_ADMIN'];
        <%_ if (enableTranslation){ _%>
        this.languageService.getAll().then((languages) => {
            this.languages = languages;
        });
        <%_ } _%>
    }

    clear () {
        this.activeModal.dismiss('cancel');
    }

    save () {
        this.isSaving = true;
        if (this.user.id !== null) {
            this.userService.update(this.user).subscribe(response => this.onSaveSuccess(response), () => this.onSaveError());
        } else {<% if (!enableTranslation){ %>
            this.user.langKey = 'en';<% } %>
            this.userService.create(this.user).subscribe(response => this.onSaveSuccess(response), () => this.onSaveError());
        }
    }
    private onSaveSuccess (result) {
        this.isSaving = false;
        this.activeModal.dismiss(result);
    }

    private onSaveError () {
        this.isSaving = false;
    }

}

<form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm" show-validation>

    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"
                (click)="clear()">&times;</button>
        <h4 class="modal-title" id="myUserLabel" jhi-translate="userManagement.home.createOrEditLabel">
            Create or edit a User</h4>
    </div>
    <div class="modal-body">
        <jhi-alert-error></jhi-alert-error>
        <div class="form-group">
            <label jhi-translate="global.field.id">ID</label>
            <input type="text" class="form-control" name="id"
                   [(ngModel)]="user.id" readonly>
        </div>

        <div class="form-group">
            <label class="control-label" jhi-translate="userManagement.login">Login</label>
            <input type="text" class="form-control" name="login" #loginInput="ngModel"
                   [(ngModel)]="user.login" required minlength=1 maxlength=50 pattern="^[_'.@A-Za-z0-9-]*$">

            <div *ngIf="loginInput.dirty && loginInput.invalid">
                <p class="help-block"
                   *ngIf="loginInput.errors.required" jhi-translate="entity.validation.required">
                    This field is required.
                </p>

                <p class="help-block"
                   *ngIf="loginInput.errors.maxlength" jhi-translate="entity.validation.maxlength"
                   translate-value-max="50">
                    This field cannot be longer than 50 characters.
                </p>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label" jhi-translate="userManagement.firstName">First Name</label>
            <input type="text" class="form-control" name="firstName" #firstNameInput="ngModel"
                   [(ngModel)]="user.firstName" maxlength="50">

            <div *ngIf="firstNameInput.dirty && firstNameInput.invalid">
                <p class="help-block"
                   *ngIf="firstNameInput.errors.maxlength" jhi-translate="entity.validation.maxlength"
                   translate-value-max="50">
                    This field cannot be longer than 50 characters.
                </p>
            </div>
        </div>
        <div class="form-group">
            <label jhi-translate="userManagement.lastName">Last Name</label>
            <input type="text" class="form-control" name="lastName" #lastNameInput="ngModel"
                   [(ngModel)]="user.lastName" maxlength="50">

            <div *ngIf="lastNameInput.dirty && lastNameInput.invalid">
                <p class="help-block"
                   *ngIf="lastNameInput.errors.maxlength" jhi-translate="entity.validation.maxlength"
                   translate-value-max="50">
                    This field cannot be longer than 50 characters.
                </p>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label" jhi-translate="userManagement.email">Email</label>
            <input type="email" class="form-control" name="email" #emailInput="ngModel"
                   [(ngModel)]="user.email" required maxlength="100">

            <div *ngIf="emailInput.dirty && emailInput.invalid">
                <p class="help-block"
                   *ngIf="emailInput.errors.required" jhi-translate="entity.validation.required">
                    This field is required.
                </p>

                <p class="help-block"
                   *ngIf="emailInput.errors.maxlength" jhi-translate="entity.validation.maxlength"
                   translate-value-max="100">
                    This field cannot be longer than 100 characters.
                </p>
				<p class="help-block"
                   *ngIf="emailInput.errors.email" jhi-translate="global.messages.validate.email.invalid">
                    Your e-mail is invalid.
                 </p>
            </div>
        </div>
        <div class="form-group">
            <label for="activated">
                <input [disabled]="user.id === null" type="checkbox" id="activated" name="activated" [(ngModel)]="user.activated">
                <span jhi-translate="userManagement.activated">Activated</span>
            </label>
        </div>

        <%_ if (enableTranslation){ _%>
        <div class="form-group" *ngIf="languages && languages.length > 0">
            <label jhi-translate="userManagement.langKey">Lang Key</label>
            <select class="form-control" id="langKey" name="langKey" [(ngModel)]="user.langKey">
                <option *ngFor="let language of languages" [value]="language">{{language | findLanguageFromKey}}</option>
            </select>
        </div>
        <%_ } _%>
        <div class="form-group">
            <label jhi-translate="userManagement.profiles">Profiles</label>
            <select class="form-control" multiple name="authority" [(ngModel)]="user.authorities">
                <option *ngFor="let authority of authorities" [value]="authority">{{authority}}</option>
            </select>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" (click)="clear()">
            <span class="glyphicon glyphicon-ban-circle"></span>&nbsp;<span
            jhi-translate="entity.action.cancel">Cancel</span>
        </button>
        <button type="submit" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
            <span class="glyphicon glyphicon-save"></span>&nbsp;<span jhi-translate="entity.action.save">Save</span>
        </button>
    </div>
</form>
