// sandbox/admin/src/main/webapp/app/modules/administration/gateway/gateway.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Badge, Table, Button } from 'reactstrap';

import { gatewayRoutes } from '../administration.reducer';

export interface IGatewayPageProps extends StateProps, DispatchProps {}

export class GatewayPage extends React.Component<IGatewayPageProps> {
  componentDidMount() {
    this.props.gatewayRoutes();
  }

  metadata = instance => {
    const spans = [];
    Object.keys(instance).map((key, index) => {
      spans.push(
        <span key={key.toString() + 'value'}>
          <Badge key={key.toString() + '-containerbadge'} className="font-weight-normal">
            <Badge key={key.toString() + '-badge'} color="info" className="font-weight-normal" pill>
              {key}
            </Badge>
            {instance[key]}
          </Badge>
        </span>
      );
    });
    return spans;
  };

  badgeInfo = info => {
    if (info) {
      if (info.status === 'UP') {
        return <Badge color="success">{info.status}</Badge>;
      } else {
        return <Badge color="danger">{info.status}</Badge>;
      }
    } else {
      return <Badge color="warning">?</Badge>;
    }
  };

  instanceInfo = route => {
    if (route) {
      return (
        <Table striped responsive>
          <tbody>
            {route.serviceInstances.map((instance, i) => (
              <tr key={instance.instanceInfo + '-info'}>
                <td>
                  <a href={instance.uri} target="_blank" rel="noopener noreferrer">
                    {instance.uri}
                  </a>
                </td>
                <td>{this.badgeInfo(instance.instanceInfo)}</td>
                <td>{this.metadata(instance.metadata)}</td>
              </tr>
            ))}
          </tbody>
        </Table>
      );
    }
  };

  gatewayRoutes = () => {
    if (!this.props.isFetching) {
      this.props.gatewayRoutes();
    }
  };

  render() {
    const { routes, isFetching } = this.props;
    return (
      <div>
        <h2>Gateway</h2>
        <p>
          <Button onClick={this.gatewayRoutes} color={isFetching ? 'danger' : 'primary'} disabled={isFetching}>
            <FontAwesomeIcon icon="sync" />
            &nbsp;
            <Translate component="span" contentKey="health.refresh.button">
              Refresh
            </Translate>
          </Button>
        </p>

        <Table striped responsive>
          <thead>
            <tr key="header">
              <th>
                <Translate contentKey="gateway.routes.url">URL</Translate>
              </th>
              <th>
                <Translate contentKey="gateway.routes.service">Service</Translate>
              </th>
              <th>
                <Translate contentKey="gateway.routes.servers">Available servers</Translate>
              </th>
            </tr>
          </thead>
          <tbody>
            {routes.map((route, i) => (
              <tr key={`routes-${i}`}>
                <td>{route.path}</td>
                <td>{route.serviceId}</td>
                <td>{this.instanceInfo(route)}</td>
              </tr>
            ))}
          </tbody>
        </Table>
      </div>
    );
  }
}

const mapStateToProps = storeState => ({
  routes: storeState.administration.gateway.routes,
  account: storeState.authentication.account,
  isFetching: storeState.administration.loading,
});

const mapDispatchToProps = { gatewayRoutes };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(GatewayPage);

// test-integration/qq/src/main/webapp/app/admin/gateway/gateway.component.ts
import { Component, OnInit } from '@angular/core';

import { GatewayRoutesService } from './gateway-routes.service';
import { GatewayRoute } from './gateway-route.model';

@Component({
  selector: 'jhi-gateway',
  templateUrl: './gateway.component.html',
  providers: [GatewayRoutesService],
})
export class GatewayComponent implements OnInit {
  gatewayRoutes: GatewayRoute[] = [];
  updatingRoutes = false;

  constructor(private gatewayRoutesService: GatewayRoutesService) {}

  ngOnInit(): void {
    this.refresh();
  }

  refresh(): void {
    this.updatingRoutes = true;
    this.gatewayRoutesService.findAll().subscribe(gatewayRoutes => {
      this.gatewayRoutes = gatewayRoutes;
      this.updatingRoutes = false;
    });
  }
}

<div>
  <h2>
    <span id="gateway-page-heading" jhiTranslate="gateway.title">Gateway</span>

    <button class="btn btn-primary float-end" (click)="refresh()" (disabled)="(updatingRoutes)">
      <fa-icon icon="sync"></fa-icon> <span jhiTranslate="gateway.refresh.button">Refresh</span>
    </button>
  </h2>

  <h3 jhiTranslate="gateway.routes.title">Current routes</h3>

  <div class="table-responsive">
    <table class="table table-striped" aria-describedby="gateway-page-heading">
      <thead>
        <tr>
          <th scope="col" jhiTranslate="gateway.routes.url">URL</th>
          <th scope="col" jhiTranslate="gateway.routes.service">Service</th>
          <th scope="col" jhiTranslate="gateway.routes.servers">Available servers</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let route of gatewayRoutes">
          <td>{{ route.path }}</td>
          <td>{{ route.serviceId }}</td>
          <td>
            <div *ngIf="route.serviceInstances.length === 0" class="label label-danger" jhiTranslate="gateway.routes.error">
              Warning: no server available!
            </div>

            <div class="table-responsive">
              <table class="table table-striped" *ngIf="route">
                <tr *ngFor="let instance of route.serviceInstances">
                  <td>
                    <a href="{{ instance.uri }}" target="_blank">{{ instance.uri }}</a>
                  </td>
                  <td>
                    <div *ngIf="instance.instanceInfo" class="badge bg-{{ instance.instanceInfo.status === 'UP' ? 'success' : 'danger' }}">
                      {{ instance.instanceInfo.status }}
                    </div>
                    <div *ngIf="!instance.instanceInfo" class="badge bg-warning">?</div>
                  </td>
                  <td>
                    <span *ngFor="let entry of instance.metadata | keyvalue">
                      <span class="badge bg-default fw-normal">
                        <span class="badge rounded-pill bg-info fw-normal">{{ entry.key }}</span>
                        {{ entry.value }}
                      </span>
                    </span>
                  </td>
                </tr>
              </table>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
